# PREDICTING RESTAURANT FOOD COST:
### DEVELOPER: THIRUMURUGAN RAMAR

### IMPORT DATASETS

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from datetime import datetime
import os

In [3]:
train_data = pd.read_excel("Data_Train.xlsx")
test_data = pd.read_excel("Data_Test.xlsx")

In [4]:
train_data.head()

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300

In [5]:
test_data.head()

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES
0,CASUAL DINING,4085,"North Indian, Chinese, Mughlai, Kebab",12noon – 12midnight (Mon-Sun),Noida,Sector 18,4.3,564 votes
1,QUICK BITES,12680,"South Indian, Fast Food, Pizza, North Indian",7am – 12:30AM (Mon-Sun),Mumbai,Grant Road,4.2,61 votes
2,CASUAL DINING,1411,"North Indian, Seafood, Biryani, Chinese",11am – 11:30pm (Mon-Sun),Mumbai,Marine Lines,3.8,350 votes
3,None,204,Biryani,"9am – 10pm (Mon, Wed, Thu, Fri, Sat, Sun), 10:...",Faridabad,NIT,3.8,1445 votes
4,QUICK BITES,13453,"South Indian, Kerala",11am – 10pm (Mon-Sun),Kochi,Kaloor,3.6,23 votes

In [6]:
train_data.describe()

       RESTAURANT_ID          COST
count   12690.000000  12690.000000
mean     7759.134121    655.252246
std      4504.874150    627.003540
min         0.000000     20.000000
25%      3863.250000    300.000000
50%      7740.000000    500.000000
75%     11688.750000    800.000000
max     15573.000000  14000.000000

## Exploratory data analysis:

### Feauture check : TRAIN DATA

In [7]:
print("\nEDA ON TRAIN DATA\n")
print("-"*30)
print("\nColumns : \n", train_data.columns)
print("\n\nNumber of Columns : ", len(train_data.columns))
print("\nNumber of Rows : ",len(train_data))
print("\n\nData Types :\n", train_data.dtypes)
print("\nContains Empty cells : ", train_data.isnull().values.any())
print("\nTotal empty cells by column :\n", train_data.isnull().sum(), "\n\n")

EDA ON TRAIN DATA

------------------------------

Columns :
 Index(['TITLE', 'RESTAURANT_ID', 'CUISINES', 'TIME', 'CITY', 'LOCALITY',
       'RATING', 'VOTES', 'COST'],
      dtype='object')


Number of Columns :  9

Number of Rows :  12690


Data Types :
 TITLE            object
RESTAURANT_ID     int64
CUISINES         object
TIME             object
CITY             object
LOCALITY         object
RATING           object
VOTES            object
COST              int64
dtype: object

Contains Empty cells :  True

Total empty cells by column :
 TITLE               0
RESTAURANT_ID       0
CUISINES            0
TIME                0
CITY              112
LOCALITY           98
RATING              2
VOTES            1204
COST                0
dtype: int64

### Feauture check: Test data

In [8]:
print("\nEDA ON TEST DATA\n")
print("-"*30)
print("\nColumns : \n", test_data.columns)
print("\n\nNumber of Columns : ", len(test_data.columns))
print("\nNumber of Rows : ",len(test_data))
print("\n\nData Types :\n", test_data.dtypes)
print("\nContains Empty cells : ", test_data.isnull().values.any())
print("\nTotal empty cells by column :\n", test_data.isnull().sum(), "\n\n")

EDA ON TEST DATA

------------------------------

Columns :
 Index(['TITLE', 'RESTAURANT_ID', 'CUISINES', 'TIME', 'CITY', 'LOCALITY',
       'RATING', 'VOTES'],
      dtype='object')


Number of Columns :  8

Number of Rows :  4231


Data Types :
 TITLE            object
RESTAURANT_ID     int64
CUISINES         object
TIME             object
CITY             object
LOCALITY         object
RATING           object
VOTES            object
dtype: object

Contains Empty cells :  True

Total empty cells by column :
 TITLE              0
RESTAURANT_ID      0
CUISINES           0
TIME               0
CITY              35
LOCALITY          30
RATING             2
VOTES            402
dtype: int64

## DATA ANALYSIS

#### 1)COMBINING TEST AND TRAIN:

In [9]:
data_temp = [train_data[['TITLE', 'RESTAURANT_ID', 'CUISINES', 'TIME', 'CITY', 'LOCALITY','RATING', 'VOTES']], test_data]
data_temp = pd.concat(data_temp)
data_temp

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes
5,CASUAL DINING,5618,"North Indian, Chinese, Seafood, Biryani",12noon – 12:30AM (Mon-Sun),Mumbai,Vile Parle West,4.0,550 votes
6,CAFÉ,4383,"Cafe, Chinese, Pizza, North Indian, Burger","12noon – 11:30pm (Mon, Tue, Thu, Fri, Sat, Sun...",Bangalore,Koramangala 6th Block,4.1,509 votes
7,MICROBREWERY,1249,Bar Food,1pm – 1am (Mon-Sun),Gurgaon,Sector 29,4.3,1612 votes
8,QUICK BITES,7062,"South Indian, North Indian",7am – 10:30pm (Mon-Sun),Bangalore,Bannerghatta Road,3.9,101 votes
9,QUICK BITES,10109,North Indian,"11am – 2pm, 4pm – 10:30pm (Mon-Sun)",Hyderabad,Dilsukhnagar,3.3,219 votes
10,CASUAL DINING,38,"North Indian, Chinese, Fast Food, Biryani",12:30pm – 12:30AM (Mon-Sun),Bangalore,Koramangala 5th Block,4.1,244 votes
11,"QUICK BITES,BEVERAGE SHOP",844,"Fast Food, Burger, Beverages","11am – 12:15AM (Mon, Tue, Wed, Thu, Fri, Sun)...",Bangalore,Indiranagar,4.0,274 votes
12,CASUAL DINING,938,"Arabian, Mughlai",11am – 11pm (Mon-Sun),Kochi,Chullickal,3.4,15 votes
13,CASUAL DINING,4319,South Indian,11am – 11:30pm (Mon-Sun),Kochi,Edappally,-,NaN
14,QUICK BITES,15024,Maharashtrian,"Closed (Mon),11am – 11pm (Tue-Sun)",Thane West,Majiwada,4.0,160 votes
15,"CASUAL DINING,IRANI CAFE",12401,"Parsi, Hyderabadi","11:30am – 11:30pm (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Jubilee Hills,4.5,2499 votes
16,CASUAL DINING,5254,"North Indian, Fast Food",7:30am – 12midnight (Mon-Sun),Mumbai,Borivali West,3.6,319 votes
17,CASUAL DINING,8259,"North Indian, Hyderabadi, Chinese",11am – 12midnight (Mon-Sun),Hyderabad,Nagole,3.5,121 votes
18,CASUAL DINING,4009,"Chinese, Thai",11am – 11:45pm (Mon-Sun),Andheri Lokhandwala,Andheri Lokhandwala,3.6,535 votes
19,"BAKERY,QUICK BITES",11841,"Bakery, Fast Food, Momos","Closed (Mon),9am – 10pm (Tue-Sun)",New Delhi,Krishna Nagar,4.1,350 votes
20,CASUAL DINING,6465,"Continental, European",9:30am – 10pm (Mon-Sun),Hyderabad,Hitech City,4.2,400 votes
21,QUICK BITES,1048,"North Indian, Rolls, Momos",10:30am – 11:30pm (Mon-Sun),New Delhi,Karol Bagh,4.0,1327 votes
22,None,12499,"North Indian, Fast Food, Mughlai, Rolls",11am – 3am (Mon-Sun),New Delhi,SDA,4.0,1191 votes
23,CASUAL DINING,10412,"Andhra, Chinese, North Indian, Biryani","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Bangalore,Thippasandra,3.9,533 votes
24,CAFÉ,2389,"Cafe, Italian, Chinese",11am – 11pm (Mon-Sun),New Delhi,Dwarka,4.2,493 votes
25,QUICK BITES,6551,"Biryani, North Indian",12noon – 11pm (Mon-Sun),Kochi,Kakkanad,3.8,372 votes
26,CASUAL DINING,13446,"North Indian, Chinese, BBQ","12:30pm – 11pm (Mon-Thu),12:30pm – 11:30pm...",Bangalore,HSR,3.4,105 votes
27,"BAR,CASUAL DINING",10277,Italian,"Closed (Mon),12noon – 3pm, 6pm – 11pm (Tue-Sun)",Chennai,Vadapalani,4.1,178 votes
28,BAR,4222,"Finger Food, North Indian, Continental, Italian",11am – 11pm (Mon-Sun),Chennai,Neelangarai,4.3,150 votes
29,PUB,6577,"Finger Food, Continental, Asian, North Indian",12:30pm – 1am (Mon-Sun),Bangalore,Koramangala 5th Block,4.2,2456 votes
...,...,...,...,...,...,...,...,...
4201,QUICK BITES,13547,"Biryani, South Indian",7am – 11pm (Mon-Sun),Gurgaon,Sector 37,3.5,22 votes
4202,QUICK BITES,9386,"Biryani, Fast Food",11am – 11pm (Mon-Sun),Chennai,Thousand Lights,4.2,232 votes
4203,QUICK BITES,12971,"South Indian, Biryani, North Indian","12noon – 3:30pm, 7:30pm – 11pm (Mon-Fri),12noo...",Chennai,Thuraipakkam,4.1,1697 votes
4204,BAKERY,15219,Bakery,10am – 10pm (Mon-Sun),Chennai,Perungudi,3.2,31 votes
4205,BAKERY,141,"Bakery, Desserts",11am – 11pm (Mon-Sun),Bangalore,New BEL Road,3.8,26 votes
4206,FINE DINING,4325,"European, Continental, North Indian",24 Hours (Mon-Sun),New Delhi,Rajendra Place,4.2,749 votes
4207,QUICK BITES,6158,"South Indian, North Indian, Chinese",7am – 11pm (Mon-Sun),Chennai,K.K. Nagar,3.4,26 votes
4208,CASUAL DINING,11799,"Chinese, North Indian",11:30am – 12midnight (Mon-Sun),Mumbai,Worli,3.6,251 votes
4209,CASUAL DINING,4992,"Biryani, Chinese, Mughlai, North Indian, Hyder...",10am – 2am (Mon-Sun),Hyderabad,Kondapur,4.0,125 votes
4210,CASUAL DINING,11680,"Chinese, North Indian, Mughlai","11am – 4pm, 7pm – 12midnight (Mon-Sun)",Mumbai,Santacruz East,3.3,312 votes
4211,"QUICK BITES,BAKERY",2943,"Fast Food, Bakery, Chinese",8am – 4am (Mon-Sun),Hyderabad,Ameerpet,3.2,1246 votes
4212,CASUAL DINING,6204,North Indian,"Closed (Mon),10am – 11:45pm (Tue-Sun)",Mumbai,Kalbadevi,4.0,371 votes
4213,CASUAL DINING,14205,"North Indian, South Indian, Chinese",11am – 11pm (Mon-Sun),Hyderabad,Manikonda,2.6,62 votes
4214,QUICK BITES,10521,"Fast Food, North Indian, South Indian",8am – 10pm (Mon-Sun),Bangalore,JP Nagar,3.7,174 votes
4215,DESSERT PARLOR,6448,"Ice Cream, Desserts",11am – 12:30AM (Mon-Sun),Mumbai,Powai,4.3,1265 votes
4216,QUICK BITES,499,"Chinese, North Indian, Arabian",11:30am – 11pm (Mon-Sun),Chennai,Tambaram,3.6,171 votes
4217,"BAR,CASUAL DINING",14508,"European, Mediterranean, Italian, Sushi","7pm – 1:30am (Mon-Tue),12noon – 1:30am (Wed-Sun)",Mumbai,Juhu,4.1,1239 votes
4218,None,11667,"North Indian, Biryani",12:30pm – 10:15pm (Mon-Sun),Bangalore,Jalahalli,3.3,6 votes
4219,CASUAL DINING,6412,"Biryani, Hyderabadi, Chinese",11:30am – 11:30pm (Mon-Sun),Bangalore,Malleshwaram,4.1,226 votes
4220,CASUAL DINING,6199,"South Indian, North Indian, Fast Food, Chinese...",7am – 10pm (Mon-Sun),Mumbai,Mulund West,3.9,197 votes
4221,CASUAL DINING,3265,"North Indian, Mughlai, Chinese",9am – 1am (Mon-Sun),Mumbai,Goregaon East,3.6,441 votes
4222,QUICK BITES,6973,"North Indian, Chinese, Kebab, Juices","12noon – 4pm, 7pm – 11pm (Mon-Sun)",Bangalore,JP Nagar,3.8,245 votes
4223,CASUAL DINING,6887,"Sindhi, Street Food","11:30am – 4pm, 7pm – 11:30pm (Mon-Sun)",Mumbai,Lower Parel,NEW,NaN
4224,QUICK BITES,331,"Kerala, South Indian","12noon – 4pm, 7pm – 10:30pm (Mon-Sat),12noon –...",Bangalore,Indiranagar,3.8,410 votes
4225,QUICK BITES,1670,"North Indian, Mughlai, Chinese","6am – 12:30AM (Mon, Tue, Wed, Thu, Sat, Sun), ...",Mumbai,Grant Road,4.0,197 votes
4226,CASUAL DINING,9057,"North Indian, Mughlai, Chinese",11:30am – 11:30pm (Mon-Sun),New Delhi,Punjabi Bagh,3.9,287 votes
4227,None,1247,"Biryani, North Indian, Sandwich, Salad, Wraps",11am – 1am (Mon-Sun),Bangalore,HSR Layout,4.3,469 votes
4228,QUICK BITES,8617,"Continental, North Indian",9:30am – 10:30pm (Mon-Sun),Faridabad,Sector 86,3.7,53 votes
4229,QUICK BITES,6485,"Rolls, Beverages","11am – 11:30pm (Mon, Tue, Wed, Thu, Sat, Sun),...",Kochi,Kochi,-,NaN
4230,QUICK BITES,2421,Mughlai,5pm – 1am (Mon-Sun),Bandra West,Perry Cross Road,3.7,63 votes

#### 2)TITLE ANALYSIS:

In [10]:
titles = list(data_temp['TITLE'])

In [11]:
maxi =1
for i in titles :
    if len(i.split(',')) > maxi:
         maxi = len(i.split(','))
print("\n\n Max titles in a cell : ", maxi)

 Max titles in a cell :  2

In [12]:
all_titles = []

for i in titles :
    if len(i.split(',')) == 1:
         all_titles.append(i.split(',')[0].strip().upper())
    else :
        for it in range(len(i.split(','))):
            all_titles.append(i.split(',')[it].strip().upper())
            
len(all_titles)

18865

In [13]:
print("\n\nNumber of Unique Titles : ", len(pd.Series(all_titles).unique()))

Number of Unique Titles :  25

In [14]:
print("\n\nUnique Titles:\n", pd.Series(all_titles).unique())

Unique Titles:
 ['CASUAL DINING' 'BAR' 'QUICK BITES' 'DESSERT PARLOR' 'CAFÉ'
 'MICROBREWERY' 'BEVERAGE SHOP' 'IRANI CAFE' 'BAKERY' 'NONE' 'PUB'
 'FINE DINING' 'SWEET SHOP' 'LOUNGE' 'FOOD COURT' 'FOOD TRUCK' 'MESS'
 'KIOSK' 'CLUB' 'CONFECTIONERY' 'DHABA' 'MEAT SHOP' 'COCKTAIL BAR'
 'PAAN SHOP' 'BHOJANALYA']

In [15]:
all_titles = list(pd.Series(all_titles).unique())
all_titles

['CASUAL DINING',
 'BAR',
 'QUICK BITES',
 'DESSERT PARLOR',
 'CAFÉ',
 'MICROBREWERY',
 'BEVERAGE SHOP',
 'IRANI CAFE',
 'BAKERY',
 'NONE',
 'PUB',
 'FINE DINING',
 'SWEET SHOP',
 'LOUNGE',
 'FOOD COURT',
 'FOOD TRUCK',
 'MESS',
 'KIOSK',
 'CLUB',
 'CONFECTIONERY',
 'DHABA',
 'MEAT SHOP',
 'COCKTAIL BAR',
 'PAAN SHOP',
 'BHOJANALYA']

#### 3)CUISINE ANALYSIS:

In [16]:
cuisines = list(data_temp['CUISINES'])

maxi = 1
for i in cuisines :
    if len(i.split(',')) > maxi:
         maxi = len(i.split(','))
         
print("\n\nMaximum cuisines in a Cell : ", maxi)

Maximum cuisines in a Cell :  8

In [17]:
all_cuisines = []

for i in cuisines :
    if len(i.split(',')) == 1:
         all_cuisines.append(i.split(',')[0].strip().upper())
    else :
        for it in range(len(i.split(','))):
            all_cuisines.append(i.split(',')[it].strip().upper())
len(all_cuisines)

43278

In [18]:
print("\n\nNumber of Unique Cuisines : ", len(pd.Series(all_cuisines).unique()))
print("\n\nUnique Cuisines:\n", pd.Series(all_cuisines).unique())

Number of Unique Cuisines :  130


Unique Cuisines:
 ['MALWANI' 'GOAN' 'NORTH INDIAN' 'ASIAN' 'MODERN INDIAN' 'JAPANESE'
 'CHINESE' 'BIRYANI' 'HYDERABADI' 'TIBETAN' 'DESSERTS' 'SEAFOOD' 'CAFE'
 'PIZZA' 'BURGER' 'BAR FOOD' 'SOUTH INDIAN' 'FAST FOOD' 'BEVERAGES'
 'ARABIAN' 'MUGHLAI' 'MAHARASHTRIAN' 'PARSI' 'THAI' 'BAKERY' 'MOMOS'
 'CONTINENTAL' 'EUROPEAN' 'ROLLS' 'ANDHRA' 'ITALIAN' 'BBQ' 'FINGER FOOD'
 'TEA' 'AMERICAN' 'HEALTHY FOOD' 'COFFEE' 'INDONESIAN' 'KOREAN' 'NEPALESE'
 'ICE CREAM' 'MEXICAN' 'KERALA' 'INDIAN' 'MITHAI' 'STREET FOOD'
 'MALAYSIAN' 'VIETNAMESE' 'IRANIAN' 'KEBAB' 'JUICES' 'SANDWICH'
 'MEDITERRANEAN' 'SALAD' 'GUJARATI' 'RAJASTHANI' 'TEX-MEX' 'ROAST CHICKEN'
 'BURMESE' 'CHETTINAD' 'NORTH EASTERN' 'LEBANESE' 'COFFEE AND TEA' 'GRILL'
 '' 'BIHARI' 'BENGALI' 'LUCKNOWI' 'AWADHI' 'STEAK' 'FRENCH' 'PORTUGUESE'
 'WRAPS' 'SRI LANKAN' 'ORIYA' 'ETHIOPIAN' 'KONKAN' 'SUSHI' 'SPANISH'
 'RUSSIAN' 'MANGALOREAN' 'TURKISH' 'BUBBLE TEA' 'AFGHAN' 'NAGA'
 'SINGAPOREAN' 'GERMAN' 'MIDDLE EASTERN' 'SINDHI' 'CANTONESE' 'HOT POT'
 'PAN ASIAN' 'SATAY' 'DUMPLINGS' 'KASHMIRI' 'RAW MEATS' 'DRINKS ONLY'
 'MOROCCAN' 'PANINI' 'CAFE FOOD' 'CHARCOAL CHICKEN' 'BELGIAN' 'MONGOLIAN'
 'TAMIL' 'AFRICAN' 'PAAN' 'ASSAMESE' 'HOT DOGS' 'POKÉ' 'BRITISH' 'BOHRI'
 'FUSION' 'ARMENIAN' 'SOUTH AMERICAN' 'GREEK' 'PAKISTANI' 'PERUVIAN'
 'CUISINE VARIES' 'IRISH' 'MULTI CUISINE' 'JEWISH' 'VEGAN' 'ORIENTAL'
 'MODERN AUSTRALIAN' 'EGYPTIAN' 'FISH AND CHIPS' 'BRAZILIAN' 'MISHTI'
 'FALAFEL' 'HAWAIIAN']

In [19]:
all_cuisines = list(pd.Series(all_cuisines).unique())
all_cuisines

['MALWANI',
 'GOAN',
 'NORTH INDIAN',
 'ASIAN',
 'MODERN INDIAN',
 'JAPANESE',
 'CHINESE',
 'BIRYANI',
 'HYDERABADI',
 'TIBETAN',
 'DESSERTS',
 'SEAFOOD',
 'CAFE',
 'PIZZA',
 'BURGER',
 'BAR FOOD',
 'SOUTH INDIAN',
 'FAST FOOD',
 'BEVERAGES',
 'ARABIAN',
 'MUGHLAI',
 'MAHARASHTRIAN',
 'PARSI',
 'THAI',
 'BAKERY',
 'MOMOS',
 'CONTINENTAL',
 'EUROPEAN',
 'ROLLS',
 'ANDHRA',
 'ITALIAN',
 'BBQ',
 'FINGER FOOD',
 'TEA',
 'AMERICAN',
 'HEALTHY FOOD',
 'COFFEE',
 'INDONESIAN',
 'KOREAN',
 'NEPALESE',
 'ICE CREAM',
 'MEXICAN',
 'KERALA',
 'INDIAN',
 'MITHAI',
 'STREET FOOD',
 'MALAYSIAN',
 'VIETNAMESE',
 'IRANIAN',
 'KEBAB',
 'JUICES',
 'SANDWICH',
 'MEDITERRANEAN',
 'SALAD',
 'GUJARATI',
 'RAJASTHANI',
 'TEX-MEX',
 'ROAST CHICKEN',
 'BURMESE',
 'CHETTINAD',
 'NORTH EASTERN',
 'LEBANESE',
 'COFFEE AND TEA',
 'GRILL',
 '',
 'BIHARI',
 'BENGALI',
 'LUCKNOWI',
 'AWADHI',
 'STEAK',
 'FRENCH',
 'PORTUGUESE',
 'WRAPS',
 'SRI LANKAN',
 'ORIYA',
 'ETHIOPIAN',
 'KONKAN',
 'SUSHI',
 'SPANISH',
 'RUSSIAN',
 'MANGALOREAN',
 'TURKISH',
 'BUBBLE TEA',
 'AFGHAN',
 'NAGA',
 'SINGAPOREAN',
 'GERMAN',
 'MIDDLE EASTERN',
 'SINDHI',
 'CANTONESE',
 'HOT POT',
 'PAN ASIAN',
 'SATAY',
 'DUMPLINGS',
 'KASHMIRI',
 'RAW MEATS',
 'DRINKS ONLY',
 'MOROCCAN',
 'PANINI',
 'CAFE FOOD',
 'CHARCOAL CHICKEN',
 'BELGIAN',
 'MONGOLIAN',
 'TAMIL',
 'AFRICAN',
 'PAAN',
 'ASSAMESE',
 'HOT DOGS',
 'POKÉ',
 'BRITISH',
 'BOHRI',
 'FUSION',
 'ARMENIAN',
 'SOUTH AMERICAN',
 'GREEK',
 'PAKISTANI',
 'PERUVIAN',
 'CUISINE VARIES',
 'IRISH',
 'MULTI CUISINE',
 'JEWISH',
 'VEGAN',
 'ORIENTAL',
 'MODERN AUSTRALIAN',
 'EGYPTIAN',
 'FISH AND CHIPS',
 'BRAZILIAN',
 'MISHTI',
 'FALAFEL',
 'HAWAIIAN']

#### 4)CITY ANALYSIS:

In [20]:
all_cities = list(data_temp['CITY'])

for i in range(len(all_cities)):
    if type(all_cities[i]) == float:
        all_cities[i] = 'NOT AVAILABLE'
    all_cities[i] = all_cities[i].strip().upper()

In [21]:
print("\n\nNumber of Unique cities (Including NOT AVAILABLE): ", len(pd.Series(all_cities).unique()))

Number of Unique cities (Including NOT AVAILABLE):  445

In [22]:
all_cities = list(pd.Series(all_cities).unique())
all_cities

['THANE',
 'CHENNAI',
 'MUMBAI',
 'BANGALORE',
 'GURGAON',
 'HYDERABAD',
 'KOCHI',
 'THANE WEST',
 'ANDHERI LOKHANDWALA',
 'NEW DELHI',
 'ANDHERI WEST',
 'MALAD EAST',
 '682036',
 'BANGALOR',
 'NAVI MUMBAI',
 'BANDRA WEST',
 'DELHI',
 'NOIDA',
 'BANGALORE-560066',
 'SECUNDERABAD',
 'NOT AVAILABLE',
 'INDIA',
 'MADHURANAGAR',
 'CHENNAI TEYNAMPET',
 'FARIDABAD',
 'CHEMBUR.',
 'MAHARASHTRA',
 'OPP GURUDWARA SHAKURPUR',
 'TELAGANA LAND LINE:040-48507016',
 'GHAZIABAD',
 'KARNATAKA',
 'KERALA',
 'EDAPPALLY',
 'KADAVANTHRA',
 'ERNAKULAM CIRCLE KOCHI',
 'BENGALORE',
 'NEAR RELIANCE FRESH',
 'KILPAUK',
 'BENGALURU',
 'KOTHAGUDA',
 'GOREGAON WEST',
 'BANGLORE',
 'TAMIL NADU',
 'KAKKANAD',
 'KOCHI ELAMKULAM',
 'OUTER RING ROAD',
 'MULUND EAST',
 'SECUNDERABAD MAIN ROAD NEAR SIGNAL NMREC COLLEGE',
 'TELANGANA',
 'PONNURUNI KOCHI',
 'GACHIBOWLI',
 'SEMMANCHERI',
 '5TH MAIN TEACHERS COLONY KORAMANGALA BLOCK 1 BANGALORE 560034',
 'MUMBAI MAHIM',
 'POWAI (NEXT TO POWAI PLAZA)',
 'DOMBIVALI EAST',
 'KOCHI VYTTILA',
 'KANDIVALI',
 'KOCHI PALARIVATTOM',
 'DEWAN RAMA ROAD',
 'GURUGRAM',
 'SECTOR 51 NOIDA',
 'KALOOR',
 'BESANT NAGAR',
 'ARUMBAKKAM CHENNAI-600106.',
 'ADJACENT TO COMMERCIAL STREET',
 'DELHI NCR',
 'DWARKA',
 '682035.',
 'KALYAN WEST',
 'AVADI',
 'KONDAPUR',
 'MEHDIPATNAM',
 'GANDIPET',
 'VELACHERY',
 'PALLAVARAM',
 'VIJAYA NAGAR',
 'BTM LAYOUT',
 'CHENNAI 600034.',
 'METRO PILLAR NO 21. METTUGUDA MAIN ROAD NEAR RAILWAY DEGREE COLLEGE.',
 'CHENNAI - 600040',
 'JP NAGAR BANGALORE',
 'MADHAPUR',
 'ERNAKULAM',
 'SARJAPUR',
 'WHITEFIELD BANGALORE',
 'KOCHI CHULLICKAL',
 'KOCHI-683101',
 'BANGALORE - 560076',
 'ROHINI',
 'HYDERABAD BEHIND VACS PASTRIES',
 'HYDERABAD NEERUS EMPORIUM.',
 'NAVI MUMBAI.',
 'KAROL BAGH',
 'PERUNGUDI',
 'THYKOODAM',
 'GREATER NOIDA',
 'BANGALORE.',
 'KHAIRATABAD',
 'CHULLICKAL',
 'GRANT ROAD WEST',
 'HITECH CITY',
 'WEST MAREDPALLY',
 'MUMBAI - 400007',
 'CHENNAI PADUR',
 'CHANDER NAGAR NEW DELHI',
 'NEDUMBASSERY',
 'MG ROAD',
 'NAYA NAGAR MIRA ROAD',
 'PITAMPURA',
 'LOWER PAREL',
 'HBR LAYOUT',
 'TELANGANA 500003',
 'RAJIV GANDHI NAGAR',
 'NEW DELHI.',
 'MEDAVAKKAM',
 'SATHYA NAGAR',
 'P.O KOCHI',
 'BEHIND RAMALAYAM TEMPLE',
 'PALARIVATTOM',
 'BRIGADE ROAD',
 'MUMBAI.',
 'MUMBAI ANDHERI EAST',
 'VIRAR WEST',
 'B-1 STAGE',
 'CHENNAI KOVALAM',
 'HYDERABAD.',
 'ALUVA',
 'TELANGANA 500034',
 'IOB BANK KAMALA NAGAR',
 'HSR LAYOUT',
 'MARINE DRIVE',
 'DLF GALLERIA',
 'NALLATHAMBI MAIN ROAD',
 'CHENNAI OPP: VASANTH & CO',
 'CITYPARK',
 'KARNATAKA 560103',
 'BHAYANDAR',
 'ALUVA CIRCLE',
 'THAMMENAHALLI VILLAGE',
 'SG PALYA',
 'ATTAPUR.',
 'NEAR SHANGRILLA BUS STOP',
 'KHAR (WEST)',
 'ROAD 3',
 'KUKATPALLY',
 'FARIDABD',
 'TELANGANA 500032',
 'DILSUKHNAGAR',
 'MOGAPPAIR. CHENNAI',
 'NEAR MUNRSHWARA TEMPLE',
 'OFF BRIGADE ROAD',
 'KHAR WEST',
 'POTHERI',
 'CHENNAI PERUNGUDI',
 'CHENNAI THURAIPAKKAM',
 'OMR KARAPAKKAM',
 'HYDERABAD-500032',
 'MUMBAI DOMBIVALI EAST',
 'CHENNAI THOUSAND LIGHTS',
 'MAHIM',
 'LINGAMPALLY',
 'POWAI',
 'NEW DELHI-110024',
 'CHENNAI- 600107',
 'KERALA 683104',
 'VASAI WEST.',
 'THANE (W)',
 'NEAR SANTOSH BANJARA HYDERABAD',
 'BANASWADI (NEXT TO INDIAN BANK) BANGALORE',
 'BTM BANGALORE',
 'GREATER KAILASH 2 NEW DELHI',
 'SECUNDERABAD ECIL',
 'BANGALORE KORAMANGALA 7TH BLOCK',
 'BANGALORE : 560085',
 'GACHIBOWLI HYDERABAD',
 'CPR LAYOUT HARLUR MAIN ROAD OPPOSITE TO OZONE EVER GREEN APARTMENT BANGALORE -',
 'ECR NEELANKARAI CHENNAI 600115',
 'WARD X11',
 'PERUMBAVOOR',
 'MIRA RAOD EAST',
 'KERALA 682013',
 'CHENNAI.',
 'POKHRAN ROAD 2',
 'UTTAR PRADESH',
 'KARNATAKA 560102',
 'MUMBAI - 400013',
 'NAHARPAR',
 'HOSUR ROAD',
 'NEAR BHARAT PETROLEUM.',
 'CHENNAI (BANG OPPOSITE INDIAN BANK)',
 'SRIRAM NAGAR',
 'WEST MUMBAI',
 'VYTTILA',
 'BANJARA HILLS',
 'MALAPALLIPURAM P .O THRISSUR',
 'ANDHERI WEST MUMBAI',
 'KARNATAKA 560043',
 'PANAMPILLY NAGAR',
 'BORIVALI EAST.',
 'ECIL',
 'JUBILEE HILLS',
 'AMRIT KAUR MARKET OPPOSITE NEW DELHI RAILWAY STATION PAHARGANJ',
 'CHENNAI OPPOSITE 5C BUS STAND',
 'TELENGANA',
 'KOCHI RAVIPURAM',
 'RAJANPADA',
 'MAHABALIPURAM',
 'SECUNDERABAD. WE HAVE NO BRANCHES.',
 'TELANGANA 500081',
 'GURGOAN',
 'ELAMAKKARA',
 'SECTOR 1',
 'BANDRA W',
 'KOLATHUR',
 'CHENNAI MAHABALIPURAM',
 '3RD STREET',
 'MUMBAI CHAKALA',
 'BORIVALI WEST',
 'RODEO DRIVE SECTOR 49',
 'PALLIMUKKU',
 'DELHI 110085',
 'SECTOR 51',
 'CHAMPAPET',
 'ANDAVAR NAGAR',
 'BANGALORE - 560103',
 'KERALA 690525',
 'OPP MUKTESHWAR ASHRAM POWAI',
 'NUNGAMBAKKAM',
 'BK GUDA',
 'JOGESHWARI (W) MUMBAI',
 'KUKATAPALLY',
 'NEAR SECTOR 110 NOIDA',
 'NAVALLUR',
 'BESIDE EXCELLENCY GARDENS',
 'MUMBAI - 80',
 'BEGUMPET',
 'MAHARAJA HOTEL BESIDE GARDANIA BAR',
 'ASHOK VIHAR PHASE 1',
 'TRIVANDRUM',
 'KOCHI-18',
 'NARAYANGUDA',
 'THEVERA',
 'CHENNAI-40',
 'PALM BEACH ROAD',
 'EAST COAST ROAD (ECR)',
 'RAMAPURAM',
 'CHENNAI CHROMPET',
 'NANDANAM',
 'SAKET',
 'MG ROAD ERNAKULAM',
 'ANDHERI LOKHANDWALA.',
 'INDIRANAGAR',
 'THIRUVANMIYUR',
 'AMBATTUR',
 'BANGLAORE',
 'CHENNAI - 34 LANDMARK - NEAR LOYOLA COLLEGE',
 'ANNA NAGAR WEST',
 'OLD RAILWAY ROAD',
 'EAST MUMBAI',
 'KANAKAPURA ROAD BANGLORE',
 'KOCHI KAKKANAD',
 'KALYAN',
 'NEAR RAMLILA GROUND',
 'SERILINGAMPALLY',
 'HIMAYATH NAGAR',
 'NALLALA STREET',
 'ANNA SALAI',
 'OLD DELHI',
 'WAGLE ESTATE',
 '1ST STAGE',
 'KOCHI-16',
 'KOCHI INTERNATIONAL AIRPORT VIP ROAD',
 'FIRST STREET',
 'CHENN AI',
 '6 & 7 - 4/64 SUBHASH NAGAR',
 '1ST TAVAREKERE',
 'PERAMBUR',
 'VAISHALI GHAZIABAD',
 'THANISANDRA',
 'BLOCK F',
 'SECTOR 7 DWARKA',
 'OPPOSITE BARATHI GAS COMPANY',
 'VADAPALANI',
 'KONDAPUR.',
 'BADLAPUR WEST.',
 'KALAMASSERY',
 'PALAVAKKAM',
 'TCS SYNERGY PARK',
 'BTM 1ST STAGE',
 'MAHADEVPURA',
 'NEW BEL ROAD 560054',
 'VELIAVEETIL HOUSE VIVEKANANDA NAGAR ELAMAKKARA',
 'SHOLINGANALLUR',
 'MAHARASHTRA 400102',
 'LOWER PAREL WEST',
 'TRIPUNITHURA',
 'MOGAPPAIR',
 'TELANGANA 500070',
 'JP NAGAR',
 'NAVI-MUMBAI',
 'ASHOK NAGAR',
 'MARATHAHALLI',
 'HARIDWAR APARTMENTS',
 'KERALA 682001 INDIA',
 'KARNATAKA 560037',
 'KERALA 683585',
 'CHENNAI. (NEAR HOTEL MATSHYA)',
 'INDIRAPURAM',
 'BEGUMPET HYDERABAD',
 'MANIKONDA',
 'BANGALORE LAND MARK ABOVE MAHAVEER HARD WARE',
 'KERALA 682304',
 'RAJARAJESHWARI NAGAR BANGALORE',
 'GST ROAD',
 'FORT KOCHI',
 'LAHARI APARTMENTS',
 'RAMANTHAPUR',
 'MULUND WEST',
 'GURGAON HARYANA INDIA',
 'NEW DELHI..NEAR BY SBI BANK',
 'KOCHI ALUVA 102',
 'PHASE 1 BANGALORE',
 'HYDERABAD MANIKONDA',
 'MUMBAI THIS IS A DELIVERY & TAKE-AWAY RESTAURANT ONLY.',
 '10TH AVENUE',
 'UPPAL',
 'NEW DELHI 110075',
 'NIZAMPET',
 'ULSOO',
 'BANGALORE 560076',
 'PVR PLAZA CINEMA BUILDING CONNAUGHT PLACE',
 'GURGAON HARYANA',
 'CHROMEPET',
 'KERALA 682024',
 'JANAKPURI',
 'SECUNDERABAD.',
 'B.B.M.P EAST (KARNATAKA) - 560049',
 'TAMBARAM',
 'MALLESHWARAM BANGALORE',
 'VADAPALANI.',
 'DIST. CENTER NEW DELHI',
 'BANGALORE ROAD',
 'KOCHI.',
 'THANE MUMBAI',
 'KADUBESANAHALLI BANGALORE',
 'VASAI WEST',
 'MIG HOUSING SOCIETY',
 'HARYANA',
 'BORIVALI WEST.',
 'GOLF COURSE ROAD',
 'KHAR MUMBAI',
 'NEAR JYOTHINIVAS COLLEGE',
 'ANNA NAGAR EAST',
 'MASAB TANK',
 'VASAI MUMBAI',
 'PANATHUR MAIN ROAD',
 'NEAR ANDHERI WEST STATION',
 'OPPOSITE TO WESTERN SIDE OF ITPL SERVICE GATE',
 'KALKAJI',
 'APR CHAMBERS',
 'TAMIL NADU 600102',
 'MAHARASHTRA.',
 'GANDHINAGAR RD',
 'NEAR ANDHERI EAST STATION',
 'WHITEFIELD',
 'KERALA 682036',
 'MIRA ROAD THANE MUMBAI',
 'INDIA GATE NEW DELHI',
 'BANGALORE - 560095',
 'SHOLINGANALLUR. CHENNAI',
 'CHENNAI (ABOVE BOMBAY BRASSERIE)',
 'CHENNAI 37',
 '682024',
 'GIRGAUM',
 'GREATER KAILASH 1 (GK 1) NEW DELHI',
 'KURLA (W)',
 'MUMBAI 400015',
 'THANE WEST THANE WEST',
 'KOCHI PANAMPILLY NAGAR',
 'MARAD',
 'MAHARASHTRA 400092',
 'NEAR SECTOR 34',
 'MEHDIPATNAM HYDERABAD',
 'NALLAGANDLA',
 'VANDALUR',
 'CHENNAI 40',
 'SECUNDERBAD',
 'MM NAGAR',
 'MUMBAI 400070',
 'CHITTETHUKKARA',
 'BTM',
 'DOMBIVLI',
 'SAHAKARA NAGAR',
 'MOHAMMAD ALI ROAD MUMBAI',
 'CHENNAI 600040',
 'TAVAREKERE MAIN ROAD',
 'COMMUNITY CENTRE',
 'KERALA 682022',
 'DELH.',
 'SECTOR-6 NOIDA 201301',
 'KAARAIKUDI COMPLEX',
 'THIRUVANMIYUR (OPP EUROKIDS LB ROAD)',
 'VIRAR MUMBAI',
 'TOLICHOWKI',
 'HYDERABA',
 'KERALA 682305',
 'ALWARPET',
 'KERALA 682015',
 'MUMBAI VEERA DESAI AREA',
 'KERALA 682018',
 'KERALA 682028',
 'SURARAM',
 'CHENNAI VELACHERY',
 'FORUM SUJANA MALL OPPOSITE TO MALAYSIAN TOWNSHIP',
 'OLD HAFEEZPET',
 'YOUSUFGUDA',
 'CHENNAI-600008',
 'MUMBAI ULHASNAGAR',
 'JOGESHWARI WEST MUMBAI',
 'CHEPAUK',
 'CHOWPATTY',
 'CHURCH STREET',
 'BALAVINAYAGAR NAGAR CHENNAI',
 'T-NAGAR CHENNAI',
 'RA PURAM',
 'HYDERABAD.STAR HYPERMARKET OPPOSITE SIDE SERVICE ROAD',
 'CHENNAI INJAMBAKKAM',
 'MUMBAI MUMBRA',
 'HABSIGUDA',
 'KURLA MUMBAI',
 'TELANGANA 500027',
 'CHENNA',
 'KERALA 682021',
 'KANDIVALI WEST',
 'CHENNAI-119',
 'NOIDA EXTENTION',
 'SHIHAB THANGAL ROAD',
 'NEW DELHI 110011',
 'MIUMBAI',
 'BORIVALI (W) MUMBAI: 400 092.',
 'VANASTHALIPURAM',
 'KK ROAD',
 'CHENNAI - 600018',
 'OPPOSITE ELLORA BUILDING']

#### 5)LOCALITY ANALYSIS:

In [23]:
all_localities = list(data_temp['LOCALITY'])

for i in range(len(all_localities)):
    if type(all_localities[i]) == float:
        all_localities[i] = 'NOT AVAILABLE'
    all_localities[i] = all_localities[i].strip().upper()
        
print("\n\nNumber of Unique Localities (Including NOT AVAILABLE) : ", len(pd.Series(all_localities).unique()))

Number of Unique Localities (Including NOT AVAILABLE) :  1611

In [24]:
all_localities = list(pd.Series(all_localities).unique())
all_localities

['DOMBIVALI EAST',
 'RAMAPURAM',
 'SALIGRAMAM',
 'BANDRA WEST',
 'LOWER PAREL',
 'VILE PARLE WEST',
 'KORAMANGALA 6TH BLOCK',
 'SECTOR 29',
 'BANNERGHATTA ROAD',
 'DILSUKHNAGAR',
 'KORAMANGALA 5TH BLOCK',
 'INDIRANAGAR',
 'CHULLICKAL',
 'EDAPPALLY',
 'MAJIWADA',
 'JUBILEE HILLS',
 'BORIVALI WEST',
 'NAGOLE',
 'ANDHERI LOKHANDWALA',
 'KRISHNA NAGAR',
 'HITECH CITY',
 'KAROL BAGH',
 'SDA',
 'THIPPASANDRA',
 'DWARKA',
 'KAKKANAD',
 'HSR',
 'VADAPALANI',
 'NEELANGARAI',
 'KORATTUR',
 'DLF CYBER CITY',
 'VERSOVA',
 'PALARIVATTOM',
 'BESANT NAGAR',
 'INTERNATIONAL AIRPORT',
 'SHOLINGANALLUR',
 'MG ROAD',
 'NUNGAMBAKKAM',
 'KR PURAM',
 'KONDAPUR',
 'ULSOOR',
 'KALOOR',
 'BEGUM BAZAAR',
 'SECTOR 15',
 'FILM CITY ROAD',
 'WHITEFIELD',
 'CHITTOOR ROAD',
 'RAJAJINAGAR',
 'BANASWADI',
 'PANAMPILLY NAGAR',
 'RAJINDER NAGAR',
 'TARNAKA',
 'KERALA',
 'T. NAGAR',
 'JALAHALLI',
 'GREATER KAILASH (GK) 2',
 'KALAMASSERY',
 'KENGERI',
 'MAZGAON',
 'TRIPLICANE',
 'BTM',
 'KALWA',
 'MATTANCHERRY',
 'KALKAJI',
 'ROHINI',
 'KURLA COMPLEX',
 'SATYANIKETAN',
 'KANDIVALI WEST',
 'GACHIBOWLI',
 'ELECTRONIC CITY',
 'BHAYANDAR',
 'NERUL',
 'CITY MARKET',
 'PALI HILL',
 'EAST OF KAILASH',
 'VIJAY NAGAR',
 'UTTAM NAGAR',
 'NEAR ELAMKULAM',
 'KORAMANGALA 3RD BLOCK',
 'NEW BEL ROAD',
 'KACHEGUDA',
 'NEAR ANDHERI WEST STATION',
 'DELHI UNIVERSITY-GTB NAGAR',
 'LINGAMPALLY',
 'NANGANALLUR',
 'CHURCH STREET',
 'KORAMANGALA 1ST BLOCK',
 'ANNA NAGAR EAST',
 'POONAMALLE',
 'PURASAIWALKAM',
 'MARINE DRIVE',
 'DADAR WEST',
 'KALYAN NAGAR',
 'KODAMBAKKAM',
 'SOHNA ROAD',
 'JP NAGAR',
 'SECTOR 53',
 'UPPAL',
 'VASAI',
 'JOGESHWARI',
 'CONNAUGHT PLACE',
 'ELAMKULAM',
 'KAMMANAHALLI',
 'KANDIVALI EAST',
 'NOT AVAILABLE',
 'SHASTRI NAGAR - LOKHANDWALA',
 'KOTHAPET',
 'JNU',
 'TELANGANA 500084',
 'BANASHANKARI',
 'SHAHDARA',
 'GREATER KAILASH 2 (GK 2)',
 'NIZAMPET',
 'MAROL MUMBAI',
 'POTHERI',
 'BREACH CANDY',
 '4 BUNGALOWS',
 'RAJOURI GARDEN',
 'BEHIND ALLAHABAD BANK',
 'TEYNAMPET',
 'MADHAPUR',
 'RAJARAJESHWARI NAGAR',
 'NEAR ANDHERI EAST STATION',
 'S D ROAD',
 'MEHDIPATNAM',
 'VYTTILA',
 'SAROOR NAGAR',
 'JUHU',
 'MANIKONDA',
 'PUNJABI BAGH',
 'K.K. NAGAR',
 'THOUSAND LIGHTS',
 'ALUVA',
 'MALAD WEST',
 'NALLAKUNTA',
 'JEEVAN BHIMA NAGAR',
 'VASANT KUNJ',
 'FORT',
 'FORT KOCHI',
 'MIRA ROAD',
 'JAYANAGAR',
 'ABIDS',
 'VENNALA',
 'LAKDIKAPUL',
 'PANJAGUTTA',
 'BASAVESHWARA NAGAR',
 'KUKATPALLY',
 'SANTACRUZ WEST',
 'LB NAGAR',
 'ARUMBAKKAM',
 'HABSIGUDA',
 'ANDHERI WEST',
 'MARATHAHALLI',
 'HAUZ KHAS VILLAGE',
 'GIRGAUM',
 'KARAPAKKAM',
 'HIMAYATH NAGAR',
 'RAILWAY STATION ROAD',
 'SAHAKARA NAGAR',
 'KALBADEVI',
 'DLF PHASE 4',
 'LODHI ROAD',
 'BANDRA EAST',
 'SAINIK FARMS',
 'AMBERNATH',
 'TILAK NAGAR',
 'AEROCITY',
 'ASHOK NAGAR',
 'ADYAR',
 'SEMMANCHERI',
 'VIKASPURI',
 'KANCHIPURAM DISTRICT',
 'CBD-BELAPUR',
 'SECTOR 63',
 'MYSORE ROAD',
 'TOLI CHOWKI',
 'NEAR MARINE DRIVE',
 'PERUNGUDI',
 'GOPALAPURAM',
 'NAVALLUR',
 'EAST PATEL NAGAR',
 'ADIKMET',
 'SECTOR 125',
 'GOLF COURSE ROAD',
 'PALARIVATTOM KOCHI',
 'BEGUMPET',
 'VIRUGAMBAKKAM',
 'KOMPALLY',
 'WILSON GARDEN',
 'PALLAVARAM',
 'AZAD NAGAR',
 'ASHOK VIHAR PHASE 4',
 'THANE WEST',
 'DLF PHASE 3',
 'DODDATHOGURU ELECTRONIC CITY',
 'GST ROAD',
 'BTM 1 STAGE BTM',
 'MUMBAI',
 'VILE PARLE EAST',
 'GREEN PARK',
 'CHENGALPATTU',
 'NEAR JEEVAN JYOTI APARTMENT',
 'WZ- 16A NEAR TIKONA PARK NEAR METRO PILLAR 658 UTTAM NAGAR',
 'GREATER KAILASH 1 (GK 1)',
 'NEAR SECTOR 72',
 'CHENNAI',
 'L B NAGAR',
 'MAHAKALI',
 'HYDERBAD',
 'POWAI',
 'KHAR',
 'INDIRAPURAM',
 'SECTOR 45',
 'KALYAN WEST',
 'MAHIM',
 'MALAKPET',
 'PAREL',
 'TOLICHOWKI',
 'FRAZER TOWN',
 'SECTOR 37',
 'SECTOR 61',
 'PALLIMUKKU',
 'CV RAMAN NAGAR',
 'LAVELLE ROAD',
 'BARAKHAMBA ROAD',
 'GOREGAON EAST',
 'SARJAPUR ROAD',
 'BENGALURU',
 'VELACHERY',
 'NEAR SECTOR 50',
 'K K NAGAR',
 'GRANT ROAD',
 'MADIPAKKAM',
 'HILL ROAD',
 'MULUND WEST',
 'A S RAO NAGAR',
 'INJAMBAKKAM',
 'VASHI',
 'ECIL',
 'NEAR OBERON MALL',
 'SECTOR 14',
 'KOVALAM',
 'KORAMANGALA 6 BLOCK',
 'CHEMBUR',
 'SCB ROAD',
 'NEAR JAIL ROAD',
 'GHATKOPAR WEST',
 'ALWARPET',
 'CHITTARANJAN PARK',
 'SECTOR 2',
 'CHROMEPET',
 'MODEL TOWN 2',
 'KILPAUK',
 'LAXMI NAGAR',
 'GEORGE TOWN',
 'PERUMBAVOOR',
 'BANJARA HILLS',
 'SAFDARJUNG',
 'EGMORE',
 'BOMMANAHALLI',
 'SECTOR 41',
 'CHANNASANDRA MAIN ROAD WHITEFIELD',
 'SECTOR 18',
 'BTM LAYOUT',
 'F1 ERNAKULAM MEDICAL CENTER',
 'CHANDA NAGAR',
 'KOYAMBEDU',
 'VASUNDHARA',
 'KACHERIPADY',
 'KORAMANGALA 7TH BLOCK',
 'NEDUMBASSERY',
 'BANDRA KURLA COMPLEX',
 'KELAMBAKKAM',
 'HENNUR',
 '65/3794 B PONOTH LANE KALOOR',
 'THEVERA',
 'MYLAPORE',
 'EDAPPALLY TOLL - POOKKATTUPADY ROAD',
 'NEAR SECTOR 125',
 'SOUTH EXTENSION PART-2',
 'AMINIJIKARAI',
 'KOPAR KHAIRANE',
 'DOMLUR',
 'NAUPADA',
 'DAVIDPURAM',
 'KASAVANAHALLI SARJAPUR ROAD',
 'JAIL ROAD',
 'BASAVANAGUDI',
 'AMBATTUR',
 'BTM LAYOUT 1',
 'SESHADRIPURAM',
 'VYPIN',
 'RED HILLS',
 'SECTOR 55',
 'THURAIPAKKAM',
 'MALLESHWARAM',
 'NIT',
 'RAJ NAGAR',
 'ST. MARKS ROAD',
 'SHANTI NAGAR',
 'SECTOR 70',
 'NEAR SECTOR 110',
 'GAUR CITY 1',
 'EKKADUTHANGAL',
 'BYCULLA',
 'CHANDIVALI',
 'NEAR CITY CENTRE METRO',
 'VANASTHALIPURAM',
 'PAHARGANJ',
 'SHALIMAR GARDEN',
 'ANNA NAGAR',
 'KARKHANA',
 'HYDERGUDA',
 'MOGAPPAIR',
 'KHANAMET',
 'MOTILAL NAGAR',
 'PURASAVAKKAM',
 'MANSINGH ROAD',
 'PORUR',
 'R K PURAM',
 'SION',
 'MASAB TANK',
 'KORAMANGALA 8TH BLOCK',
 'SANATH NAGAR',
 'MALLAPUR',
 'BOWENPALLY',
 'AMEERPET',
 'BRIGADE ROAD',
 'EDACHIRA JUNCTION',
 'PADUR',
 'VEPERY',
 'SOMAJIGUDA',
 'KARKARDOOMA',
 'MIYAPUR',
 'VASANT VIHAR',
 'MAYUR VIHAR PHASE 3',
 'BARNABY ROAD',
 'THRIKKAKARA',
 'LANGER HOUZ',
 'WASHERMENPET',
 'MATUNGA EAST',
 'SHAMSHABAD',
 'VAISHALI',
 'NARIMAN POINT',
 'MALABAR HILL',
 'MAROL',
 'VARTHUR HOBLI',
 'CHURCHGATE',
 '90 FEET ROAD',
 'SAINIKPURI',
 'NORTH KALAMASSERY',
 'GREATER NOIDA',
 'PERUMBAVOOR CIRCLE',
 'GHANSOLI',
 'ERNAKULAM',
 'NAGARBHAVI',
 'MALVIYA NAGAR',
 'KAVI NAGAR',
 'PITAMPURA',
 'SHAMIRPET',
 'OKKIYAMPET',
 'NAMPALLY',
 'MEDAVAKKAM',
 'CHETPET',
 'VALASARAVAKKAM',
 'MAHABALIPURAM',
 'JANAKPURI',
 'GEETA COLONY',
 'NEAR PITAMPURA',
 'ELAMAKKARA',
 'RAMANTHAPUR',
 'MALAD EAST',
 'WILLINGDON ISLAND',
 'MALKAJGIRI',
 'BOIGUDA',
 'S R NAGAR',
 'SECUNDERABAD',
 'SHAREEF AIRPORT ROAD CHANDRAYANAGUTTA',
 'CHETTICHIRA',
 'KOLATHUR',
 'JEEVAN BHIMA NAGAR MAIN ROAD',
 'KAGGADASAPURA',
 'MAYUR VIHAR PHASE 2',
 'RAVIPURAM',
 'THIRUVANMIYUR',
 'KALYAN',
 'WORLI',
 'EJIPURA',
 'NIT 5',
 'FILM NAGAR',
 'WEST PATEL NAGAR',
 'BELLANDUR',
 'MULUND EAST',
 'CYBER HILLS COLONY',
 'GHATKOPAR EAST',
 'YESHWANTPUR',
 'OMR SEMMANCHERRY ALAMARAM',
 'MOHAMMAD ALI ROAD',
 'SHIRDI SAI LAYOUT NEAR SAI BABA TEMPLE ROAD MARATHAHALLI',
 'SHOP 7 SHIKRUPA SOCITY',
 'SECTOR 10',
 'SECTOR 28',
 'VEERA DESAI AREA',
 'THE MYLAPORE CAFE 29',
 'HIRANANDANI GARDENS',
 'KAMLA NAGAR',
 'KAPASHERA',
 'BROOKEFIELD',
 'WEST MAMBALAM',
 'AMBERPET',
 'EGATOOR',
 'KHARGHAR',
 'MUMBAI THANE',
 'YUSUF SARAI',
 'ANNA NAGAR WEST',
 'KOTTURPURAM',
 'THAKUR VILLAGE',
 'TRIPUNITHURA',
 'OLD MADRAS ROAD',
 'KUMARSWAMY LAYOUT',
 'ROYAPETTAH',
 'SOUTH EXTENSION 2',
 'THANE',
 'NEAR TARAMANI',
 'CHENNAI-600040',
 'KORAMANGALA 4TH BLOCK',
 'SUSHANT LOK',
 'HYDERABAD',
 'HAUZ KHAS',
 'JANGPURA',
 'MARREDPALLY',
 'DAHISAR EAST',
 'SAKET',
 '4/53',
 'KALAMBOLI',
 'THOPUMPADY',
 'CHARMINAR',
 'SECTOR 50',
 'VIRAR',
 'EAST COAST ROAD (ECR)',
 'SECTOR 72',
 'ADAMBAKKAM',
 'SANKEY ROAD',
 'PERAMBUR',
 'PLOT NO 155. HOSHIYARPUR VILLAGE OPPOSITE D32',
 'ROYAPURAM',
 'NEAR PUNJABI BAGH',
 'LAJPAT NAGAR 4',
 'CHANDNI CHOWK',
 'SHENOYS',
 'PRABHADEVI',
 'VASANTH NAGAR',
 'ERRAGADDA',
 'COLABA',
 'MOTI NAGAR',
 'SECTOR 31',
 'ERNAKULAM NORTH',
 'SRINAGAR COLONY',
 'ALWAL',
 'TRIPLICANE HIGH ROAD',
 'PG ROAD',
 'CHAKALA',
 'ASHOK VIHAR PHASE 2',
 'ULHASNAGAR',
 'VANDALUR',
 'TARAMANI',
 'NAGAWARA',
 'CROSSINGS REPUBLIK',
 'SECTOR-19 AIROLI',
 'MUKHERJEE NAGAR',
 'DEFENCE COLONY',
 'UTTARAHALLI',
 'NEAR GOLE MARKET',
 'PADAMUGHAL',
 'KASARVADAVLI',
 'KHOPAT',
 'MAHAVIR NAGAR KANDIVALI WEST',
 'BORIVALI EAST',
 'BENIL ZACHARIAH ATHINILKUNNATHIL NEAR SALAFI MASJEED CHENAKARA ROAD NAD P.O KOMPARA',
 'SAKINAKA',
 'LODHI COLONY',
 'MANDAVELI',
 'TARDEO',
 'OFF RACE COURSE ROAD',
 'AIROLI',
 'SELAIYUR',
 'GOREGAON WEST',
 'NEAR ADCHINI',
 'OPPOSITE GALLERIA MARKET DLF PHASE 4',
 'MAJNU KA TILA',
 'OLD RAILWAY ROAD',
 'TUGHLAKABAD INSTITUTIONAL AREA',
 '5TH AVENUE',
 'MAJESTIC',
 'VALLUVAR ROAD',
 'KHAR WEST',
 'PREET VIHAR',
 'JASOLA',
 'MEENAKASHI KOVIL STREET',
 'CHANAKYAPURI',
 'NARAYANGUDA',
 'SANJAY NAGAR',
 'NEAR RAJESH KHANNA GARDEN. SANTACRUZ WEST',
 'INDIRAPURAM HABITAT CENTRE',
 'YELAHANKA',
 'ANGAMALI',
 'MARAD',
 'PASCHIM VIHAR',
 'RR NAGAR',
 'LINKING ROAD',
 'NEW DELHI',
 'SECTOR 62',
 'RA PURAM',
 'SARITA VIHAR',
 'SECTOR 12',
 'SAIDAPET',
 'CHOOLAIMEDU',
 'SAKI NAKA MUMBAI',
 'PANCH PAKHADI',
 'SECTOR 42',
 'SHENOY NAGAR',
 'IN FRONT OF RAJIV CHOWK METRO GATE NO -5',
 'MEDCHAL ROAD',
 'SOUTH EXTENSION 1',
 'DADAR EAST',
 'SECTOR 11',
 'CHANDRAYANAGUTTA',
 'RAMBAUG 4',
 'KIRTI NAGAR',
 'WEST PUNJABI BAGH',
 'SECTOR 49',
 'WEST K.K. NAGAR',
 'DLF PHASE 2',
 'CUNNINGHAM ROAD',
 'ST. THOMAS MOUNT',
 'GREATER KAILASH (GK) 1',
 'WADALA',
 'MADURAVOYAL',
 'CROSSING REPUBLIK',
 'NEAR BASAVANAGUDI',
 'S.A.P COLONY',
 'GUINDY',
 'KOTTIVAKKAM',
 'SECTOR 16',
 'NARAINA',
 'MAYAPURI PHASE 2',
 'S P ROAD',
 'SHIVAJINAGAR',
 'MUTTUKADU',
 'KAILASH COLONY',
 'SRIRAM NAGAR',
 'KHAN MARKET',
 'M.G. ROAD',
 'INA',
 'MOOTAIKARANCHAVADI THURAIPAKKAM',
 'SECTOR 93',
 'ANDHERI',
 'CHOWPATTY',
 'JANPATH',
 'GUDDIMALLAKPUR',
 'INDIA',
 'OPPOSITE JNU EAST GATE',
 'AMINJIKARAI',
 'ALANDUR',
 'SECTOR 8',
 'PARADISE CIRCLE',
 'SECTOR 7',
 'SOWCARPET',
 'KADAVANTHRA',
 'PANDARA ROAD MARKET',
 'KOKAPET',
 'DADAR SHIVAJI PARK',
 'TAGORE GARDEN',
 'SECTOR 23',
 'NEAR SAKET',
 '2ND FLOOR DLF PHASE 3',
 'SECTOR 38',
 'SECTOR-17 ROHINI',
 'CHOWNK 1 CHARNI ROAD',
 'MUMBAI CST AREA',
 'ASHOK VIHAR PHASE 3',
 'OLD RAJINDER NAGAR',
 'BHANDUP',
 '100 FT ROAD',
 'SECTOR 110',
 'SECTOR 25',
 'SHAHPUR JAT',
 'MALLIKA NAGAR',
 'PF LAYOUT',
 '1ST STAGE',
 'OSHIWARA',
 'GAMMA 2',
 'HSR LAYOUT',
 'METTUGUDA',
 'NEAR SECTOR 21',
 'LOKHANDWALA COMPLEX',
 'MRC NAGAR',
 'PEDDAR ROAD',
 'BALANAGAR',
 'MALLESHWARAM WEST',
 'NAJAFGARH',
 'NEAR MAYUR VIHAR PHASE 1',
 'SECTOR 104',
 'HS-6 KAILASH COLONY MARKET GREATER KAILASH-1 DELHI',
 'RAMMURTHY NAGAR',
 'TRIMULGHERRY',
 'HEBBAL',
 'SECTOR 4',
 'AZADPUR',
 'KOCHI',
 'RAJENDRA NAGAR',
 'NALASOPARA',
 '7TH PHASE',
 'FALAKNUMA',
 'SANPADA',
 'NEAR VENKATESHWARA COLLEGE',
 'UDYOG VIHAR',
 'MOGAPAIR WEST',
 'KURLA',
 'SANTACRUZ EAST',
 'MUNIRKA',
 'PRAGATHI LAYOUT',
 'ANJAIAH NAGAR',
 'PUKKATTUPADI',
 'JAYANAGAR 4TH T BLOCK',
 'LAJPAT NAGAR 1',
 'ELECTRONIC CITY PHASE 1',
 'PADMARAO NAGAR',
 'MURTHAL',
 'SILPA PARK',
 'TAMBARAM',
 'MAYUR VIHAR PHASE 1',
 'SECTOR 75',
 'NETAJI SUBHASH PLACE',
 'CHERANALLOOR',
 'VASUNDHARA ENCLAVE',
 'BELLANDUR WARD',
 'NEAR ANNA NAGAR EAST',
 'ATTAPUR',
 'ASIF NAGAR MEHDIPATNAM',
 'ANAND VIHAR',
 'KERALA 683101',
 'SECTOR 19',
 'PRASANTH LAYOUT',
 'VYTTILA ELAMKULAM',
 'SECTOR 22',
 '7 BUNGALOWS',
 'GREATER KAILASH 1 (GK1)',
 'HARYANA 121001',
 'RACE COURSE ROAD',
 '55/402B 4TH CROSS ROAD PANAMPILLY NAGAR',
 'MAGADI ROAD',
 'HIRANANDANI ESTATE',
 'JEEDIMETLA',
 'YOUSUFGUDA',
 'NACHARAM',
 'OLD AIRPORT ROAD',
 'SECTOR 54',
 'EDAPALLY',
 'MAMALLAPURAM',
 'RT NAGAR',
 'MEERPET',
 'RICHMOND TOWN',
 'SECTOR 26',
 'MAHIPALPUR',
 'CUFFE PARADE',
 'SECTOR-3',
 'LAJPAT NAGAR 2',
 'NEAR SECTOR 14',
 'PANDAV NAGAR',
 'IP EXTENSION',
 'KAMOTHE',
 'HIRANANDANI GARDENS POWAI',
 'SIKANDARPUR',
 'HUDA CITY CENTRE METRO STATION',
 'HEBBALA',
 'SHAKARPUR',
 'PEENYA',
 'MUSHEERABAD',
 'GAMMA 1',
 'PURASAIWAKKAM',
 'MOOSAPET',
 'SECTOR 13',
 'BOLGATTY',
 'SUBHASH MARKET',
 'SECTOR 17',
 'BANDRA TALAO',
 'EDAPPALLY NORTH',
 'SELECT CITYWALK MALL SAKET',
 'CHHATARPUR',
 'KANDANCHAVADI',
 'RICHMOND ROAD',
 'CHHOTA ANJAIAH NAGAR',
 'GOLE MARKET',
 'P5 GK MARG LOWER PAREL',
 'SAFDARJUNG ENCLAVE',
 'OPP DECATHLON',
 'SAROJINI NAGAR',
 'HYDER SHAHKOTE LANGER HOUZ',
 'SECTOR 81',
 'OKKIAMPET',
 'CHARMWOOD VILLAGE',
 'MIRA ROAD EAST',
 'AVADI',
 'BASHEER BAGH',
 'SECTOR 44',
 'RESIDENCY ROAD',
 'BETA 2',
 'KOTI',
 'KANAKAPURA ROAD',
 'RAMADASU STATUE',
 'OKHLA PHASE 1',
 'NEAR KUMAR PETROL BULK',
 'INORBIT MALL ROAD KUKATPALLY',
 'NANA CHOWK',
 'BALLABHGARH',
 'MALLESWRARAM',
 'SANTHOME',
 'MAHALAXMI',
 'PARK TOWN',
 'JUHU NORTH',
 'SECTOR 39',
 'MIND SPACE CENTRE',
 'SURARAM',
 'UDAY PARK',
 'NEAR PRAVASI INDUSTRIAL GOREGAON EAST',
 'SERILINGAMPALLY',
 'MAIN ROAD',
 'CHARNI ROAD',
 'SHALIMAR BAGH',
 'NEAR RTC X ROADS',
 'KANATHUR',
 'DIST ERNAKULAM',
 'CENTRE SQUARE MALL',
 'PALLIKARANAI',
 'NEW PANVEL',
 'NARENDER PARK',
 'RANI BAGH',
 'NEW FRIENDS COLONY',
 'NEAR NAGAWARA',
 'OASIS COMPLEX',
 'NEAR KACHERIPADY',
 'KUMARASWAMY LAYOUT',
 'RAVI COLONY KONDAPUR',
 'JAMA MASJID',
 '80 FEET MAIN ROAD',
 'OLD MAHABALIPURAM ROAD (OMR)',
 'GACHIBOWLI - MIYAPUR ROAD',
 '2ND MAIN ROAD',
 'BEHIND STATE BANK OF INDIA KAVI NAGAR',
 'GUJRANWALA TOWN',
 'THANE EAST',
 '(MAIN MARKET) MAYUR VIHAR PHASE 2',
 'MUMBAI BANDRA KURLA COMPLEX',
 'MOHAN NAGAR',
 'AMRAPALI LEISURE VALLEY',
 'BALAPUR',
 'GREEN COURT',
 'NEAR CHANDNI CHOWK',
 'SECTOR 21',
 'NEAR SECTOR 23',
 'ATHANI',
 '3/132 - RAMAPURAM MAIN ROAD',
 'MARINE LINES',
 'PERUMBAKKAM MAIN ROAD',
 'NEAR LEISURE VALLEY PARK',
 'JOGESHWARI WEST',
 'KHANPUR',
 'PADIVATTOM',
 'SAIDABAD COLONY',
 'NEAR MARATAHALLI',
 'ANNA SALAI',
 'B.B.M.P JALAHALLI',
 'NEAR RTA OFFICE NAGOLE',
 'YMCA JUNCTION. CHITTOOR ROAD',
 'RAMGOPALPET',
 'VATIKA INDIA SECTOR 83',
 'BTM 2ND STAGE',
 'BANDRA RECLAMATION DOCK',
 'SURANBHI ROAD',
 'BEHIND YAZOO PARK',
 'GREATER KAILASH 2 (GK2)',
 'ISHA LIFE HYDERABAD YOGA STUDIO LLP PLOT: 522; ROAD NO 27 JUBILEE HILLS',
 'SANJEEVA REDDY NAGAR',
 'MARUTHI NAGAR',
 'SAHIBABAD',
 'VARTHUR ROAD',
 'SOUTH CITY 2',
 'BESIDE DURGA TEMPLE',
 'VIKHROLI',
 'MADHAVARAM',
 'NEHRU PLACE',
 'DILSHAD GARDEN',
 'AMATEURS RIDERS CLUB MAHALAXMI RACECOURSE',
 'ARDEE CITY',
 'CARTER ROAD',
 'OLD PANVEL',
 'MANJAPETTY ALUVA PERUMBAVOOR ROAD',
 'RAJA GARDEN',
 'TKR COLLEGE ROAD MEERPET',
 'BIAL INTERNATIONAL AIRPORT',
 '8TH BLOCK MOGAPPAIR WEST',
 'KEMPS CORNER',
 'NEAR SECTOR 83',
 'NEAR FOCUS HOSPITAL CHAMPAPET SAROOR NAGAR',
 'NEAR PALAM',
 'SECTOR 83',
 'SURAJ KUND',
 '1-7-172/1 ECIL OPPOSITE',
 'MANPADA',
 'BHOOPASANDRA MAIN ROAD',
 'NEAR SATELLITE TOWER OPPOSITE SANTOSH GARAGE FILM CITY ROAD GOREGAON EAST',
 'KAUSHAMBI',
 'KOVILAMBAKKAM',
 'ILYAZ NAGAR',
 'NAVI MUMBAI',
 'PALACE ROAD',
 'PRASHANT VIHAR',
 'NEAR BEGUM BAZAAR',
 'SADASHIV NAGAR',
 'SECTOR 38 - A',
 'SOUTH KALAMASSERY',
 'SECTOR 56',
 'LAWRENCE ROAD',
 'RODEO DRIVE SECTOR 49',
 'KOCHI ERNAKULAM',
 '1ST FLOOR',
 'CIVIL LINES',
 'MOULA ALI',
 'NEAR ROHINI',
 'GHODBUNDER ROAD',
 'RAMASWAMY COLONY',
 'KHEL GAON MARG',
 '14/90',
 'OLD PALLAVARAM',
 'NEAR UPPAL',
 'DARYAGANJ',
 'OUTER CIRCLE CONNAUGHT PLACE',
 'VIRAR WEST',
 'SUBHASH NAGAR',
 'GAUR CITY 2',
 'PALAVAKKAM',
 'MEHRAULI',
 'VENKAT NARAYANA ROAD T. NAGAR',
 'BEGUR HOBLI',
 'KALYAN WEST. KALYAN',
 'CHANDRAYANGUTTA',
 'OPPOSITE INORBIT MALL',
 'WEST SAIDAPET',
 'MAIN MARKET MALVIYA NAGAR',
 'ASHOK VIHAR PHASE 1',
 '1ST RIGHT',
 'NEREDMET',
 'OPPOSITE AL-AMEEN SCHOOL NEAR LULU MALL NH 17 EDAPPALLY',
 'GHANSI BAZAAR',
 'MIRA BHAYANDAR',
 'ADITYA HEIGHTS',
 'PUKALAKKATT COMPLEX PALARIVATTOM VYTILLA ROAD PALARIVATTOM',
 'NERUL EAST',
 'ACHARYA DOCTOR SARVEPALLI RADHAKRISHNAN ROAD',
 'ALPHA 2',
 'K.R PURAM',
 'VENKATESHWARA LAYOUT',
 'BHANDUP WEST',
 'SHOP 5 PLOT 2 VILLAGE SAHBERI CROSSING REPUBLIK',
 'SAHAKAR NAGAR',
 'SAND PADA',
 'GANDIPET',
 'MALWANI MALAD WEST',
 'CHAWRI BAZAR',
 'TAMBARAM SENATORIUM',
 'APOLLO ROAD',
 'JNTU',
 'BHAYANDAR WEST',
 'UTHANDI',
 'KALOOR - KADAVANTHARA ROAD',
 'HUDA MARKET',
 'OMR ROAD SHOLINGANALLUR',
 'TELANGANA 500053',
 'CHANDER NAGAR',
 '1ST LANE',
 'ERI SCHEME',
 'BANERJI ROAD',
 'NAVALUR',
 'OUTER RING ROAD',
 'REST HOUSE ROAD',
 'EAST TAMBARAM',
 '18TH A ROAD',
 'SECTOR 73',
 '9TH MAIN YARAB NAGAR MAIN ROAD BANASHANKARI',
 'PILLAYAR KOIL STREET',
 'NOIDA GREATER NOIDA WEST',
 'THOTTAKKATTUKARA',
 'RAJIV GANDHI SALAI',
 'DELHI NCR',
 'HASTINAPURAM',
 'WEST DELHI JANAKPURI',
 'KALAMASSERY CIRCLE',
 'OKHLA PHASE 2',
 'ULWE',
 '4TH SECTOR HSR',
 'ADCHINI',
 'RANI GUNJ',
 'GIRGAON',
 'MAIN MARKET CHHATARPUR',
 'OLD BOWENPALLY',
 'NEAR BRIGADE ROAD',
 'NUCLEUS MALL',
 'KORAMANGALA',
 'T.H.KATARIA MARG',
 'LOCATION VARIES',
 'NEAR FEROZE SHAH ROAD',
 'KERALA 682003',
 'HAFEEZPET',
 '2ND STAGE BTM',
 'THRIPPUNITHURA',
 'LAKE HOMES & HIRANANDANI GARDENS',
 'LAJPAT NAGAR',
 'NEAR YOUSUFGUDA',
 'YELAHANKA NEW TOWN',
 'KERALA 682006',
 'SECTOR 132',
 'NEARER TO FISHERMEN BAR AND RESTAURENT',
 'PERUMBAKKAM',
 'SECTOR 86',
 'OPPOSITE KOTAK MAHINDRA BANK NEXT TO WOODLAND FURNITURE',
 'LOUISWADI',
 'SECTOR 3',
 '62 RAMAMURTHY NAGAR MAIN ROAD',
 'MEDAVAKAM',
 'HBR LAYOUT',
 'NEAR SUBHASH NAGAR',
 'HMT ROAD KALAMASSERY',
 'TAVAREKERE MAIN ROAD',
 'KAVADIGUDA',
 'SADAR BAZAR',
 'M BLOCK MARKET',
 'OPPOSITE BASEMENT MARKET DLF PHASE 3',
 'SOUTH BANGALORE URBAN MARATHAHALLI',
 'BANGALORE',
 'SERILINGAMPALLY MANDAL',
 'NEAR SECTOR 132',
 'DAHISAR WEST',
 'CHEMBUR EAST',
 'SECTOR 71',
 'MARVE',
 'PALAM VIHAR',
 'AKKARAI',
 'OMR FOOD STREET - AMBATTUR',
 'BANASHANKARI 3RD STAGE',
 'OPPOSITE RUBY HOSPITAL JOGESHWARI',
 'NEAR KAILASH HOSPITAL',
 'NEAR SILK BOARD BTM 2ND STAGE',
 'SECTOR 57',
 'SEAWOODS GRAND CENTRAL MALL',
 'BOULDER HILLS',
 'HOSUR ROAD',
 'PERAMBAKKAM MEDAVAKKAM',
 'SAIDULLJAB',
 'DOSA TIME #17/1',
 '359',
 'SECTOR 43',
 'OKKIYAM THURAIPAKKAM',
 'BODUPPAL',
 'MOGAPPAIR EAST',
 '5TH PHASE JP NAGAR',
 'MPL 6303',
 'OBERON MALL',
 'T NAGAR',
 'PERUMBAVOOR PO',
 'ASMITA UPAHAR 2',
 'A SOUTH RAO NAGAR',
 'SECTOR 135',
 'ZEHRA NAGAR',
 'SECTOR 33',
 'CBD BELAPUR',
 'NAUPADA POLICE STATION',
 'BEHIND BETHANY HOSPITAL',
 'NOIDA',
 'PUMP JUNCTION PERIYAR NAGAR ALUVA',
 'KERALA 682024',
 'SECTOR-16 ROHINI',
 'SECTOR 127',
 'MOGAPPAIR WEST GARDEN',
 'SECTOR 82',
 'OPPOSITE INDIAN OIL PETROL PUMP UPPAL',
 'NEAR CHRIST COLLEGE',
 'I C COLONY',
 'NEAR TEA VILLA CAFE',
 'OPPOSITE GLOMAX MALL',
 'DLF PHASE 1',
 'OPPOSITE STATE BANK OF INDIA GACHIBOWLI BRANCH',
 'GANDHINAGAR YELAHANKA',
 'NEAR SOHNA ROAD',
 'OPPOSITE ATC SHOPING MALL AS RAO NAGAR',
 'KNOWLEDGE PARK 3',
 'PONNURNI',
 'ROAD 2',
 'ALMAA EDAH',
 'VP ROAD',
 ...]

## DATA CLEANING

### CLEANING TRAIN DATA:

#### 1)TITLE CLEANING:

In [25]:
titles = list(train_data['TITLE'])

In [26]:
#max titles =2
T1 = []
T2 = []

for i in titles:
    T1.append(i.split(',')[0].strip().upper())
    try :
         T2.append(i.split(',')[1].strip().upper())
    except :
         T2.append('NONE')

# appending NONE to Unique titles list
all_titles.append('NONE')

#### 2)CLEANING CUISINES:

In [27]:
cuisines = list(train_data['CUISINES'])

In [28]:
#max cuisines = 8
C1 = []
C2 = []
C3 = []
C4 = []
C5 = []
C6 = []
C7 = []
C8 = []


for i in cuisines:
        try :
            C1.append(i.split(',')[0].strip().upper())
        except :
            C1.append('NONE')
        try :
            C2.append(i.split(',')[1].strip().upper())
        except :
            C2.append('NONE')
        try :
            C3.append(i.split(',')[2].strip().upper())
        except :
            C3.append('NONE')
        try :
            C4.append(i.split(',')[3].strip().upper())
        except :
            C4.append('NONE')
        try :
            C5.append(i.split(',')[4].strip().upper())
        except :
            C5.append('NONE')
        try :
            C6.append(i.split(',')[5].strip().upper())
        except :
            C6.append('NONE')
        try :
            C7.append(i.split(',')[6].strip().upper())
        except :
            C7.append('NONE')
        try :
            C8.append(i.split(',')[7].strip().upper())
        except :
            C8.append('NONE')

# appending NONE to Unique cuisines list
all_cuisines.append('NONE')

#### 3) CLEANING CITY AND LOCALITY:

In [29]:
localities = list(train_data['LOCALITY'])

for i in range(len(localities)):
    if type(localities[i]) == float:
        localities[i] = 'NOT AVAILABLE'
    localities[i] = localities[i].strip().upper()   

cities = list(train_data['CITY'])

for i in range(len(cities)):
    if type(cities[i]) == float:
        cities[i] = 'NOT AVAILABLE'
    cities[i] = cities[i].strip().upper()

#### 4)CLEANING RATING

In [30]:
rates = list(train_data['RATING'])

for i in range(len(rates)) :
    try:
       rates[i] = float(rates[i])
    except :
       rates[i] = np.nan

#### 5)CLEANING VOTES:

In [31]:
votes = list(train_data['VOTES'])

for i in range(len(votes)) :
    try:
       votes[i] = int(votes[i].split(" ")[0].strip())
    except :
       votes[i]=np.nan

### FORMING TRAIN DATAFRAME:

In [32]:
new_data_train = {}

new_data_train['TITLE1'] = T1
new_data_train['TITLE2'] = T2
new_data_train['RESTAURANT_ID'] = train_data["RESTAURANT_ID"]
new_data_train['CUISINE1'] = C1
new_data_train['CUISINE2'] = C2
new_data_train['CUISINE3'] = C3
new_data_train['CUISINE4'] = C4
new_data_train['CUISINE5'] = C5
new_data_train['CUISINE6'] = C6
new_data_train['CUISINE7'] = C7
new_data_train['CUISINE8'] = C8
new_data_train['CITY'] = cities
new_data_train['LOCALITY'] = localities
new_data_train['RATING'] = rates
new_data_train['VOTES'] = votes
new_data_train['COST'] = train_data["COST"]

new_data_train = pd.DataFrame(new_data_train)

In [33]:
new_data_train.head()

,TITLE1,TITLE2,RESTAURANT_ID,CUISINE1,CUISINE2,CUISINE3,CUISINE4,CUISINE5,CUISINE6,CUISINE7,CUISINE8,CITY,LOCALITY,RATING,VOTES,COST
0,CASUAL DINING,NONE,9438,MALWANI,GOAN,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,THANE,DOMBIVALI EAST,3.6,49.0,1200
1,CASUAL DINING,BAR,13198,ASIAN,MODERN INDIAN,JAPANESE,NONE,NONE,NONE,NONE,NONE,CHENNAI,RAMAPURAM,4.2,30.0,1500
2,CASUAL DINING,NONE,10915,NORTH INDIAN,CHINESE,BIRYANI,HYDERABADI,NONE,NONE,NONE,NONE,CHENNAI,SALIGRAMAM,3.8,221.0,800
3,QUICK BITES,NONE,6346,TIBETAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,BANDRA WEST,4.1,24.0,800
4,DESSERT PARLOR,NONE,15387,DESSERTS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,LOWER PAREL,3.8,165.0,300

## CLEANING TEST DATA:
##### REPEATING THE ABOVE PROCEDURES:

In [34]:
titles = list(test_data['TITLE'])

#MAX =2
T1 = []
T2 = []

for i in titles:
    T1.append(i.split(',')[0].strip().upper())
    try :
         T2.append(i.split(',')[1].strip().upper())
    except :
         T2.append('NONE')

In [35]:
cuisines = list(test_data['CUISINES'])
   
C1 = []
C2 = []
C3 = []
C4 = []
C5 = []
C6 = []
C7 = []
C8 = []


for i in cuisines:
        try :
            C1.append(i.split(',')[0].strip().upper())
        except :
            C1.append('NONE')
        try :
            C2.append(i.split(',')[1].strip().upper())
        except :
            C2.append('NONE')
        try :
            C3.append(i.split(',')[2].strip().upper())
        except :
            C3.append('NONE')
        try :
            C4.append(i.split(',')[3].strip().upper())
        except :
            C4.append('NONE')
        try :
            C5.append(i.split(',')[4].strip().upper())
        except :
            C5.append('NONE')
        try :
            C6.append(i.split(',')[5].strip().upper())
        except :
            C6.append('NONE')
        try :
            C7.append(i.split(',')[6].strip().upper())
        except :
            C7.append('NONE')
        try :
            C8.append(i.split(',')[7].strip().upper())
        except :
            C8.append('NONE')

In [36]:
cities = list(test_data['CITY'])

for i in range(len(cities)):
    if type(cities[i]) == float:
        cities[i] = 'NOT AVAILABLE'
    cities[i] = cities[i].strip().upper()

In [37]:
localities = list(test_data['LOCALITY'])

for i in range(len(localities)):
    if type(localities[i]) == float:
        localities[i] = 'NOT AVAILABLE'
    localities[i] = localities[i].strip().upper()

In [38]:
rates = list(test_data['RATING'])

for i in range(len(rates)) :
    try:
       rates[i] = float(rates[i])
    except :
       rates[i] = np.nan

In [39]:
votes = list(test_data['VOTES'])

for i in range(len(votes)) :
    try:
       votes[i] = int(votes[i].split(" ")[0].strip())
    except :
       votes[i] = np.nan

## FORMING TEST DATAFRAME:

In [40]:
new_data_test = {}

new_data_test['TITLE1'] = T1
new_data_test['TITLE2'] = T2
new_data_test['RESTAURANT_ID'] = test_data["RESTAURANT_ID"]
new_data_test['CUISINE1'] = C1
new_data_test['CUISINE2'] = C2
new_data_test['CUISINE3'] = C3
new_data_test['CUISINE4'] = C4
new_data_test['CUISINE5'] = C5
new_data_test['CUISINE6'] = C6
new_data_test['CUISINE7'] = C7
new_data_test['CUISINE8'] = C8
new_data_test['CITY'] = cities
new_data_test['LOCALITY'] = localities
new_data_test['RATING'] = rates
new_data_test['VOTES'] = votes

new_data_test = pd.DataFrame(new_data_test)

In [41]:
new_data_test.head()

,TITLE1,TITLE2,RESTAURANT_ID,CUISINE1,CUISINE2,CUISINE3,CUISINE4,CUISINE5,CUISINE6,CUISINE7,CUISINE8,CITY,LOCALITY,RATING,VOTES
0,CASUAL DINING,NONE,4085,NORTH INDIAN,CHINESE,MUGHLAI,KEBAB,NONE,NONE,NONE,NONE,NOIDA,SECTOR 18,4.3,564.0
1,QUICK BITES,NONE,12680,SOUTH INDIAN,FAST FOOD,PIZZA,NORTH INDIAN,NONE,NONE,NONE,NONE,MUMBAI,GRANT ROAD,4.2,61.0
2,CASUAL DINING,NONE,1411,NORTH INDIAN,SEAFOOD,BIRYANI,CHINESE,NONE,NONE,NONE,NONE,MUMBAI,MARINE LINES,3.8,350.0
3,NONE,NONE,204,BIRYANI,NONE,NONE,NONE,NONE,NONE,NONE,NONE,FARIDABAD,NIT,3.8,1445.0
4,QUICK BITES,NONE,13453,SOUTH INDIAN,KERALA,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,KALOOR,3.6,23.0

## DATA PRE-PROCESSING:

#### 1)MISSING VALUES:

In [42]:
new_data_train.fillna(0, inplace = True)

In [43]:
new_data_train

,TITLE1,TITLE2,RESTAURANT_ID,CUISINE1,CUISINE2,CUISINE3,CUISINE4,CUISINE5,CUISINE6,CUISINE7,CUISINE8,CITY,LOCALITY,RATING,VOTES,COST
0,CASUAL DINING,NONE,9438,MALWANI,GOAN,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,THANE,DOMBIVALI EAST,3.6,49.0,1200
1,CASUAL DINING,BAR,13198,ASIAN,MODERN INDIAN,JAPANESE,NONE,NONE,NONE,NONE,NONE,CHENNAI,RAMAPURAM,4.2,30.0,1500
2,CASUAL DINING,NONE,10915,NORTH INDIAN,CHINESE,BIRYANI,HYDERABADI,NONE,NONE,NONE,NONE,CHENNAI,SALIGRAMAM,3.8,221.0,800
3,QUICK BITES,NONE,6346,TIBETAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,BANDRA WEST,4.1,24.0,800
4,DESSERT PARLOR,NONE,15387,DESSERTS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,LOWER PAREL,3.8,165.0,300
5,CASUAL DINING,NONE,5618,NORTH INDIAN,CHINESE,SEAFOOD,BIRYANI,NONE,NONE,NONE,NONE,MUMBAI,VILE PARLE WEST,4.0,550.0,800
6,CAFÉ,NONE,4383,CAFE,CHINESE,PIZZA,NORTH INDIAN,BURGER,NONE,NONE,NONE,BANGALORE,KORAMANGALA 6TH BLOCK,4.1,509.0,600
7,MICROBREWERY,NONE,1249,BAR FOOD,NONE,NONE,NONE,NONE,NONE,NONE,NONE,GURGAON,SECTOR 29,4.3,1612.0,1600
8,QUICK BITES,NONE,7062,SOUTH INDIAN,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,BANNERGHATTA ROAD,3.9,101.0,300
9,QUICK BITES,NONE,10109,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,DILSUKHNAGAR,3.3,219.0,200
10,CASUAL DINING,NONE,38,NORTH INDIAN,CHINESE,FAST FOOD,BIRYANI,NONE,NONE,NONE,NONE,BANGALORE,KORAMANGALA 5TH BLOCK,4.1,244.0,900
11,QUICK BITES,BEVERAGE SHOP,844,FAST FOOD,BURGER,BEVERAGES,NONE,NONE,NONE,NONE,NONE,BANGALORE,INDIRANAGAR,4.0,274.0,800
12,CASUAL DINING,NONE,938,ARABIAN,MUGHLAI,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,CHULLICKAL,3.4,15.0,600
13,CASUAL DINING,NONE,4319,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,EDAPPALLY,0.0,0.0,400
14,QUICK BITES,NONE,15024,MAHARASHTRIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,THANE WEST,MAJIWADA,4.0,160.0,300
15,CASUAL DINING,IRANI CAFE,12401,PARSI,HYDERABADI,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,JUBILEE HILLS,4.5,2499.0,1400
16,CASUAL DINING,NONE,5254,NORTH INDIAN,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,BORIVALI WEST,3.6,319.0,900
17,CASUAL DINING,NONE,8259,NORTH INDIAN,HYDERABADI,CHINESE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,NAGOLE,3.5,121.0,600
18,CASUAL DINING,NONE,4009,CHINESE,THAI,NONE,NONE,NONE,NONE,NONE,NONE,ANDHERI LOKHANDWALA,ANDHERI LOKHANDWALA,3.6,535.0,600
19,BAKERY,QUICK BITES,11841,BAKERY,FAST FOOD,MOMOS,NONE,NONE,NONE,NONE,NONE,NEW DELHI,KRISHNA NAGAR,4.1,350.0,200
20,CASUAL DINING,NONE,6465,CONTINENTAL,EUROPEAN,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,HITECH CITY,4.2,400.0,350
21,QUICK BITES,NONE,1048,NORTH INDIAN,ROLLS,MOMOS,NONE,NONE,NONE,NONE,NONE,NEW DELHI,KAROL BAGH,4.0,1327.0,500
22,NONE,NONE,12499,NORTH INDIAN,FAST FOOD,MUGHLAI,ROLLS,NONE,NONE,NONE,NONE,NEW DELHI,SDA,4.0,1191.0,450
23,CASUAL DINING,NONE,10412,ANDHRA,CHINESE,NORTH INDIAN,BIRYANI,NONE,NONE,NONE,NONE,BANGALORE,THIPPASANDRA,3.9,533.0,600
24,CAFÉ,NONE,2389,CAFE,ITALIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NEW DELHI,DWARKA,4.2,493.0,700
25,QUICK BITES,NONE,6551,BIRYANI,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,KAKKANAD,3.8,372.0,400
26,CASUAL DINING,NONE,13446,NORTH INDIAN,CHINESE,BBQ,NONE,NONE,NONE,NONE,NONE,BANGALORE,HSR,3.4,105.0,700
27,BAR,CASUAL DINING,10277,ITALIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,VADAPALANI,4.1,178.0,1400
28,BAR,NONE,4222,FINGER FOOD,NORTH INDIAN,CONTINENTAL,ITALIAN,NONE,NONE,NONE,NONE,CHENNAI,NEELANGARAI,4.3,150.0,1000
29,PUB,NONE,6577,FINGER FOOD,CONTINENTAL,ASIAN,NORTH INDIAN,NONE,NONE,NONE,NONE,BANGALORE,KORAMANGALA 5TH BLOCK,4.2,2456.0,1400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12660,CASUAL DINING,BAR,1439,NORTH INDIAN,CONTINENTAL,CHINESE,BEVERAGES,NONE,NONE,NONE,NONE,MUMBAI,BANDRA WEST,0.0,0.0,1200
12661,CASUAL DINING,NONE,889,NORTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,GURGAON,NEAR SOHNA ROAD,3.4,221.0,400
12662,QUICK BITES,NONE,5399,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,MASAB TANK,3.6,46.0,200
12663,CASUAL DINING,NONE,2334,NORTH INDIAN,CHINESE,BEVERAGES,NONE,NONE,NONE,NONE,NONE,MUMBAI,CHEMBUR,3.6,133.0,600
12664,QUICK BITES,NONE,15265,CHINESE,MOMOS,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,NEAR PERAMBUR,3.7,86.0,350
12665,NONE,NONE,5679,SALAD,HEALTHY FOOD,BEVERAGES,CONTINENTAL,NONE,NONE,NONE,NONE,FARIDABAD,NIT,3.9,38.0,200
12666,QUICK BITES,NONE,11730,MUGHLAI,NORTH INDIAN,KEBAB,NONE,NONE,NONE,NONE,NONE,MUMBAI,BYCULLA,4.0,702.0,350
12667,CAFÉ,NONE,2663,CAFE,NORTH INDIAN,MOMOS,NONE,NONE,NONE,NONE,NONE,GURGAON,SECTOR 23,3.9,146.0,550
12668,FINE DINING,NONE,1939,NORTH INDIAN,SOUTH INDIAN,CHINESE,ASIAN,MEXICAN,PIZZA,BURGER,NONE,CHENNAI,GST ROAD,3.5,32.0,2600
12669,CASUAL DINING,NONE,15441,BBQ,ARABIAN,NORTH INDIAN,BIRYANI,NONE,NONE,NONE,NONE,BANGALORE,KR PURAM,4.0,736.0,900
12670,QUICK BITES,NONE,14118,NORTH INDIAN,CHINESE,MOMOS,MUGHLAI,ROLLS,THAI,NONE,NONE,NEW DELHI,JANAKPURI,3.6,40.0,500
12671,BEVERAGE SHOP,QUICK BITES,9086,JUICES,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,MARINE DRIVE,3.3,10.0,300
12672,QUICK BITES,NONE,14727,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,MAJESTIC,4.2,158.0,200
12673,NONE,NONE,12011,FAST FOOD,ROLLS,NONE,NONE,NONE,NONE,NONE,NONE,NEW DELHI,KAROL BAGH,4.0,617.0,250
12674,DESSERT PARLOR,BEVERAGE SHOP,13358,DESSERTS,BEVERAGES,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,GACHIBOWLI,4.3,590.0,350
12675,CASUAL DINING,NONE,2029,SALAD,HEALTHY FOOD,JUICES,NONE,NONE,NONE,NONE,NONE,BANDRA WEST,LINKING ROAD,4.5,2723.0,900
12676,QUICK BITES,NONE,13369,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NEW DELHI,KAROL BAGH,3.7,326.0,350
12677,NONE,NONE,14196,ROLLS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,MAHALAXMI,4.0,123.0,550
12678,DESSERT PARLOR,NONE,14003,ICE CREAM,DESSERTS,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,ANNA NAGAR EAST,3.9,59.0,350
12679,QUICK BITES,NONE,6648,ITALIAN,MEDITERRANEAN,NONE,NONE,NONE,NONE,NONE,NONE,GURGAON,DLF PHASE 3,4.3,68.0,650
12680,QUICK BITES,NONE,13798,NORTH INDIAN,FAST FOOD,DESSERTS,NONE,NONE,NONE,NONE,NONE,NEW DELHI,NEAR MALVIYA NAGAR,3.4,13.0,300
12681,CAFÉ,NONE,3241,BEVERAGES,CAFE,BAKERY,NONE,NONE,NONE,NONE,NONE,NOIDA,SECTOR 18,4.1,300.0,450
12682,QUICK BITES,NONE,8085,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI.,MOGAPPAIR,3.6,30.0,450
12683,QUICK BITES,SWEET SHOP,5430,NORTH INDIAN,SOUTH INDIAN,STREET FOOD,MITHAI,NONE,NONE,NONE,NONE,NEW DELHI,PITAMPURA,4.1,1426.0,500
12684,CASUAL DINING,NONE,8324,NORTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,NEW DELHI,MOTI NAGAR,3.8,492.0,550
12685,QUICK BITES,NONE,13228,NORTH INDIAN,BURGER,KEBAB,NONE,NONE,NONE,NONE,NONE,HYDERABAD,GACHIBOWLI,3.8,546.0,500
12686,CASUAL DINING,BAR,9686,GOAN,CONTINENTAL,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,BANDRA KURLA COMPLEX,4.3,1214.0,1800
12687,LOUNGE,NONE,11133,FINGER FOOD,CONTINENTAL,ASIAN,CHINESE,NONE,NONE,NONE,NONE,NAVI MUMBAI,VASHI,4.0,608.0,1300
12688,CASUAL DINING,NONE,6134,NORTH INDIAN,SOUTH INDIAN,CHINESE,STREET FOOD,NONE,NONE,NONE,NONE,CHENNAI,MADURAVOYAL,3.5,32.0,400
12689,CASUAL DINING,NONE,6430,NORTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,VANASTHALIPURAM,3.4,677.0,600

In [44]:
new_data_test.fillna(0, inplace = True)

In [45]:
new_data_test

,TITLE1,TITLE2,RESTAURANT_ID,CUISINE1,CUISINE2,CUISINE3,CUISINE4,CUISINE5,CUISINE6,CUISINE7,CUISINE8,CITY,LOCALITY,RATING,VOTES
0,CASUAL DINING,NONE,4085,NORTH INDIAN,CHINESE,MUGHLAI,KEBAB,NONE,NONE,NONE,NONE,NOIDA,SECTOR 18,4.3,564.0
1,QUICK BITES,NONE,12680,SOUTH INDIAN,FAST FOOD,PIZZA,NORTH INDIAN,NONE,NONE,NONE,NONE,MUMBAI,GRANT ROAD,4.2,61.0
2,CASUAL DINING,NONE,1411,NORTH INDIAN,SEAFOOD,BIRYANI,CHINESE,NONE,NONE,NONE,NONE,MUMBAI,MARINE LINES,3.8,350.0
3,NONE,NONE,204,BIRYANI,NONE,NONE,NONE,NONE,NONE,NONE,NONE,FARIDABAD,NIT,3.8,1445.0
4,QUICK BITES,NONE,13453,SOUTH INDIAN,KERALA,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,KALOOR,3.6,23.0
5,FOOD TRUCK,DESSERT PARLOR,4518,ICE CREAM,DESSERTS,NONE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,BANJARA HILLS,3.7,36.0
6,CASUAL DINING,NONE,1643,NORTH INDIAN,STREET FOOD,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NAVI MUMBAI,KHARGHAR,0.0,0.0
7,CASUAL DINING,NONE,5109,BIRYANI,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,NAVALUR,4.0,703.0
8,NONE,NONE,5606,NORTH INDIAN,CHINESE,PIZZA,FAST FOOD,NONE,NONE,NONE,NONE,NEW DELHI,IP EXTENSION,3.4,475.0
9,CASUAL DINING,NONE,14319,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,PALARIVATTOM,3.2,6.0
10,DESSERT PARLOR,QUICK BITES,4079,DESSERTS,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,ELECTRONIC CITY,3.8,166.0
11,QUICK BITES,NONE,8873,SOUTH INDIAN,NORTH INDIAN,CHINESE,STREET FOOD,NONE,NONE,NONE,NONE,CHENNAI,WEST MAMBALAM,3.7,46.0
12,CASUAL DINING,BAR,12322,FRENCH,NONE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,WORLI,4.2,518.0
13,LOUNGE,NONE,7910,FINGER FOOD,CONTINENTAL,CHINESE,NONE,NONE,NONE,NONE,NONE,BANGALORE,ULSOOR,4.1,100.0
14,CASUAL DINING,NONE,309,NORTH INDIAN,CHINESE,CONTINENTAL,NONE,NONE,NONE,NONE,NONE,HYDERABAD,ABIDS,4.1,105.0
15,CASUAL DINING,NONE,1224,BBQ,BIRYANI,CONTINENTAL,NONE,NONE,NONE,NONE,NONE,BANGALORE,MG ROAD,3.8,64.0
16,QUICK BITES,NONE,6376,CHINESE,FAST FOOD,ROLLS,STREET FOOD,NONE,NONE,NONE,NONE,MUMBAI,DAHISAR WEST,4.1,137.0
17,NONE,NONE,3931,FAST FOOD,CHINESE,MOMOS,NONE,NONE,NONE,NONE,NONE,FARIDABAD,NIT,3.8,639.0
18,QUICK BITES,NONE,2274,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,VIJAY NAGAR,4.3,315.0
19,BEVERAGE SHOP,NONE,4974,BEVERAGES,ICE CREAM,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,MG ROAD,3.4,16.0
20,CASUAL DINING,NONE,12078,NORTH INDIAN,CHINESE,SOUTH INDIAN,FAST FOOD,NONE,NONE,NONE,NONE,MUMBAI,FORT,3.6,237.0
21,CASUAL DINING,NONE,3852,NORTH INDIAN,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,ANNA SALAI,0.0,0.0
22,CASUAL DINING,PUB,380,ITALIAN,MEXICAN,CHINESE,NORTH INDIAN,AMERICAN,DESSERTS,NONE,NONE,VASAI MUMBAI,EAST,3.8,136.0
23,QUICK BITES,NONE,865,NORTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,GURGAON,DLF PHASE 4,3.4,14.0
24,QUICK BITES,NONE,8102,BIRYANI,ANDHRA,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,BANGALORE,BANASWADI,0.0,0.0
25,DESSERT PARLOR,NONE,5568,ICE CREAM,BEVERAGES,DESSERTS,NONE,NONE,NONE,NONE,NONE,HYDERABAD,JUBILEE HILLS,4.2,98.0
26,CASUAL DINING,NONE,2474,ITALIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,FARIDABAD,SECTOR 15,4.2,1356.0
27,CASUAL DINING,NONE,4696,CONTINENTAL,ITALIAN,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,BTM,0.0,0.0
28,CASUAL DINING,NONE,9659,BIRYANI,SOUTH INDIAN,NORTH INDIAN,KERALA,NONE,NONE,NONE,NONE,KOCHI,ELAMKULAM,3.7,19.0
29,QUICK BITES,NONE,14208,NORTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,BANDRA WEST,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4201,QUICK BITES,NONE,13547,BIRYANI,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,GURGAON,SECTOR 37,3.5,22.0
4202,QUICK BITES,NONE,9386,BIRYANI,FAST FOOD,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,THOUSAND LIGHTS,4.2,232.0
4203,QUICK BITES,NONE,12971,SOUTH INDIAN,BIRYANI,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,CHENNAI,THURAIPAKKAM,4.1,1697.0
4204,BAKERY,NONE,15219,BAKERY,NONE,NONE,NONE,NONE,NONE,NONE,NONE,CHENNAI,PERUNGUDI,3.2,31.0
4205,BAKERY,NONE,141,BAKERY,DESSERTS,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,NEW BEL ROAD,3.8,26.0
4206,FINE DINING,NONE,4325,EUROPEAN,CONTINENTAL,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NEW DELHI,RAJENDRA PLACE,4.2,749.0
4207,QUICK BITES,NONE,6158,SOUTH INDIAN,NORTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,CHENNAI,K.K. NAGAR,3.4,26.0
4208,CASUAL DINING,NONE,11799,CHINESE,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,WORLI,3.6,251.0
4209,CASUAL DINING,NONE,4992,BIRYANI,CHINESE,MUGHLAI,NORTH INDIAN,HYDERABADI,NONE,NONE,NONE,HYDERABAD,KONDAPUR,4.0,125.0
4210,CASUAL DINING,NONE,11680,CHINESE,NORTH INDIAN,MUGHLAI,NONE,NONE,NONE,NONE,NONE,MUMBAI,SANTACRUZ EAST,3.3,312.0
4211,QUICK BITES,BAKERY,2943,FAST FOOD,BAKERY,CHINESE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,AMEERPET,3.2,1246.0
4212,CASUAL DINING,NONE,6204,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,KALBADEVI,4.0,371.0
4213,CASUAL DINING,NONE,14205,NORTH INDIAN,SOUTH INDIAN,CHINESE,NONE,NONE,NONE,NONE,NONE,HYDERABAD,MANIKONDA,2.6,62.0
4214,QUICK BITES,NONE,10521,FAST FOOD,NORTH INDIAN,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,BANGALORE,JP NAGAR,3.7,174.0
4215,DESSERT PARLOR,NONE,6448,ICE CREAM,DESSERTS,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,POWAI,4.3,1265.0
4216,QUICK BITES,NONE,499,CHINESE,NORTH INDIAN,ARABIAN,NONE,NONE,NONE,NONE,NONE,CHENNAI,TAMBARAM,3.6,171.0
4217,BAR,CASUAL DINING,14508,EUROPEAN,MEDITERRANEAN,ITALIAN,SUSHI,NONE,NONE,NONE,NONE,MUMBAI,JUHU,4.1,1239.0
4218,NONE,NONE,11667,NORTH INDIAN,BIRYANI,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,JALAHALLI,3.3,6.0
4219,CASUAL DINING,NONE,6412,BIRYANI,HYDERABADI,CHINESE,NONE,NONE,NONE,NONE,NONE,BANGALORE,MALLESHWARAM,4.1,226.0
4220,CASUAL DINING,NONE,6199,SOUTH INDIAN,NORTH INDIAN,FAST FOOD,CHINESE,BEVERAGES,NONE,NONE,NONE,MUMBAI,MULUND WEST,3.9,197.0
4221,CASUAL DINING,NONE,3265,NORTH INDIAN,MUGHLAI,CHINESE,NONE,NONE,NONE,NONE,NONE,MUMBAI,GOREGAON EAST,3.6,441.0
4222,QUICK BITES,NONE,6973,NORTH INDIAN,CHINESE,KEBAB,JUICES,NONE,NONE,NONE,NONE,BANGALORE,JP NAGAR,3.8,245.0
4223,CASUAL DINING,NONE,6887,SINDHI,STREET FOOD,NONE,NONE,NONE,NONE,NONE,NONE,MUMBAI,LOWER PAREL,0.0,0.0
4224,QUICK BITES,NONE,331,KERALA,SOUTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,BANGALORE,INDIRANAGAR,3.8,410.0
4225,QUICK BITES,NONE,1670,NORTH INDIAN,MUGHLAI,CHINESE,NONE,NONE,NONE,NONE,NONE,MUMBAI,GRANT ROAD,4.0,197.0
4226,CASUAL DINING,NONE,9057,NORTH INDIAN,MUGHLAI,CHINESE,NONE,NONE,NONE,NONE,NONE,NEW DELHI,PUNJABI BAGH,3.9,287.0
4227,NONE,NONE,1247,BIRYANI,NORTH INDIAN,SANDWICH,SALAD,WRAPS,NONE,NONE,NONE,BANGALORE,HSR LAYOUT,4.3,469.0
4228,QUICK BITES,NONE,8617,CONTINENTAL,NORTH INDIAN,NONE,NONE,NONE,NONE,NONE,NONE,FARIDABAD,SECTOR 86,3.7,53.0
4229,QUICK BITES,NONE,6485,ROLLS,BEVERAGES,NONE,NONE,NONE,NONE,NONE,NONE,KOCHI,KOCHI,0.0,0.0
4230,QUICK BITES,NONE,2421,MUGHLAI,NONE,NONE,NONE,NONE,NONE,NONE,NONE,BANDRA WEST,PERRY CROSS ROAD,3.7,63.0

#### 2)ENCODING CATEGORICAL VARIABLES:

In [46]:
from sklearn.preprocessing import LabelEncoder

le_titles = LabelEncoder()
le_cuisines = LabelEncoder()

le_city = LabelEncoder()

le_locality = LabelEncoder()


le_titles.fit(all_titles)
le_cuisines.fit(all_cuisines)

le_city.fit(all_cities)
le_locality.fit(all_localities)

LabelEncoder()

In [47]:
new_data_train['TITLE1'] = le_titles.transform(new_data_train['TITLE1'])
new_data_train['TITLE2'] = le_titles.transform(new_data_train['TITLE2'])


new_data_train['CUISINE1'] = le_cuisines.transform(new_data_train['CUISINE1'])
new_data_train['CUISINE2'] = le_cuisines.transform(new_data_train['CUISINE2'])
new_data_train['CUISINE3'] = le_cuisines.transform(new_data_train['CUISINE3'])
new_data_train['CUISINE4'] = le_cuisines.transform(new_data_train['CUISINE4'])
new_data_train['CUISINE5'] = le_cuisines.transform(new_data_train['CUISINE5'])
new_data_train['CUISINE6'] = le_cuisines.transform(new_data_train['CUISINE6'])
new_data_train['CUISINE7'] = le_cuisines.transform(new_data_train['CUISINE7'])
new_data_train['CUISINE8'] = le_cuisines.transform(new_data_train['CUISINE8'])


new_data_train['CITY'] = le_city.transform(new_data_train['CITY'])
new_data_train['LOCALITY'] = le_locality.transform(new_data_train['LOCALITY'])

In [50]:
new_data_train.head()

,TITLE1,TITLE2,RESTAURANT_ID,CUISINE1,CUISINE2,CUISINE3,CUISINE4,CUISINE5,CUISINE6,CUISINE7,CUISINE8,CITY,LOCALITY,RATING,VOTES,COST
0,5,20,9438,74,47,92,90,90,90,90,90,408,320,3.6,49.0,1200
1,5,1,13198,7,82,62,90,90,90,90,90,75,1204,4.2,30.0,1500
2,5,20,10915,92,29,17,55,90,90,90,90,75,1261,3.8,221.0,800
3,23,20,6346,126,29,90,90,90,90,90,90,280,149,4.1,24.0,800
4,9,20,15387,34,90,90,90,90,90,90,90,280,700,3.8,165.0,300

In [49]:
new_data_test['TITLE1'] = le_titles.transform(new_data_test['TITLE1'])
new_data_test['TITLE2'] = le_titles.transform(new_data_test['TITLE2'])


new_data_test['CUISINE1'] = le_cuisines.transform(new_data_test['CUISINE1'])
new_data_test['CUISINE2'] = le_cuisines.transform(new_data_test['CUISINE2'])
new_data_test['CUISINE3'] = le_cuisines.transform(new_data_test['CUISINE3'])
new_data_test['CUISINE4'] = le_cuisines.transform(new_data_test['CUISINE4'])
new_data_test['CUISINE5'] = le_cuisines.transform(new_data_test['CUISINE5'])
new_data_test['CUISINE6'] = le_cuisines.transform(new_data_test['CUISINE6'])
new_data_test['CUISINE7'] = le_cuisines.transform(new_data_test['CUISINE7'])
new_data_test['CUISINE8'] = le_cuisines.transform(new_data_test['CUISINE8'])


new_data_test['CITY'] = le_city.transform(new_data_test['CITY'])
new_data_test['LOCALITY'] = le_locality.transform(new_data_test['LOCALITY'])
new_data_test.head()

,TITLE1,TITLE2,RESTAURANT_ID,CUISINE1,CUISINE2,CUISINE3,CUISINE4,CUISINE5,CUISINE6,CUISINE7,CUISINE8,CITY,LOCALITY,RATING,VOTES
0,5,20,4085,92,29,86,66,90,90,90,90,326,1307,4.3,564.0
1,23,20,12680,116,41,101,92,90,90,90,90,280,417,4.2,61.0
2,5,20,1411,92,112,17,29,90,90,90,90,280,759,3.8,350.0
3,20,20,204,17,90,90,90,90,90,90,90,131,1007,3.8,1445.0
4,23,20,13453,116,67,90,90,90,90,90,90,220,557,3.6,23.0

In [51]:
Y_train = new_data_train.iloc[:, -1].values  
X_train = new_data_train.iloc[:,0 : -1].values
X_test = new_data_test.iloc[:,:].values

In [52]:
Y_train

array([1200, 1500,  800, ..., 1300,  400,  600], dtype=int64)

In [53]:
X_train

array([[5.0000e+00, 2.0000e+01, 9.4380e+03, ..., 3.2000e+02, 3.6000e+00,
        4.9000e+01],
       [5.0000e+00, 1.0000e+00, 1.3198e+04, ..., 1.2040e+03, 4.2000e+00,
        3.0000e+01],
       [5.0000e+00, 2.0000e+01, 1.0915e+04, ..., 1.2610e+03, 3.8000e+00,
        2.2100e+02],
       ...,
       [1.6000e+01, 2.0000e+01, 1.1133e+04, ..., 1.5430e+03, 4.0000e+00,
        6.0800e+02],
       [5.0000e+00, 2.0000e+01, 6.1340e+03, ..., 7.0600e+02, 3.5000e+00,
        3.2000e+01],
       [5.0000e+00, 2.0000e+01, 6.4300e+03, ..., 1.5340e+03, 3.4000e+00,
        6.7700e+02]])

In [54]:
X_test

array([[5.000e+00, 2.000e+01, 4.085e+03, ..., 1.307e+03, 4.300e+00,
        5.640e+02],
       [2.300e+01, 2.000e+01, 1.268e+04, ..., 4.170e+02, 4.200e+00,
        6.100e+01],
       [5.000e+00, 2.000e+01, 1.411e+03, ..., 7.590e+02, 3.800e+00,
        3.500e+02],
       ...,
       [2.300e+01, 2.000e+01, 8.617e+03, ..., 1.364e+03, 3.700e+00,
        5.300e+01],
       [2.300e+01, 2.000e+01, 6.485e+03, ..., 6.290e+02, 0.000e+00,
        0.000e+00],
       [2.300e+01, 2.000e+01, 2.421e+03, ..., 1.136e+03, 3.700e+00,
        6.300e+01]])

## FEATURE SCALING:

In [55]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [56]:
Y_train

array([1200, 1500,  800, ..., 1300,  400,  600], dtype=int64)

In [57]:
Y_train = Y_train.reshape((len(Y_train), 1)) 
Y_train

array([[1200],
       [1500],
       [ 800],
       ...,
       [1300],
       [ 400],
       [ 600]], dtype=int64)

In [58]:
Y_train = sc.fit_transform(Y_train)
Y_train

C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

array([[ 0.86884552],
       [ 1.34733058],
       [ 0.23086546],
       ...,
       [ 1.02834054],
       [-0.40711461],
       [-0.08812458]])

In [59]:
Y_train = Y_train.ravel()
Y_train

array([ 0.86884552,  1.34733058,  0.23086546, ...,  1.02834054,
       -0.40711461, -0.08812458])

## MODELLING:

In [60]:
from sklearn.ensemble import GradientBoostingRegressor

gbr=GradientBoostingRegressor( loss = 'huber',learning_rate=0.001,n_estimators=350, max_depth=6
                              ,subsample=1,
                              verbose=False,random_state=126)
gbr.fit(X_train,Y_train)

y_pred_gbr = sc.inverse_transform(gbr.predict(X_test))

In [61]:
y_pred_gbr = pd.DataFrame(y_pred_gbr, columns = ['COST'])
y_pred_gbr

             COST
0      632.919695
1      448.642518
2      535.698524
3      482.916633
4      430.093996
5      490.899986
6      518.879700
7      610.794718
8      479.714109
9      518.879700
10     516.237573
11     452.820275
12     771.978844
13     777.672192
14     599.648734
15     486.891574
16     459.588619
17     488.278066
18     422.183709
19     466.093516
20     534.525662
21     518.879700
22     519.031354
23     457.938396
24     452.455512
25     483.722516
26     632.919695
27     517.343653
28     517.343653
29     458.773518
...           ...
4201   444.089258
4202   472.004627
4203   453.638680
4204   444.369633
4205   444.369633
4206  1236.070597
4207   450.891918
4208   534.525662
4209   578.571499
4210   534.525662
4211   474.612652
4212   599.648734
4213   518.879700
4214   455.566907
4215   443.898023
4216   480.651017
4217   771.978844
4218   463.288341
4219   578.571499
4220   553.050063
4221   597.277039
4222   495.441642
4223   518.879700
4224   466.129169
4225   495.584281
4226   555.506421
4227   526.197353
4228   446.623835
4229   457.938396
4230   447.843350

[4231 rows x 1 columns]

In [62]:
y_pred_gbr.to_excel("restaurant cost submissiongbr.xlsx", index = False )

## score:0.83642
#### ref:analyticsindiamagazine